// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.
//
// The audio session vocabulary. Import this if your stage produces or
// consumes an audio stream.

package audio

import (
	"encoding/json"
)

// Ensure the json import is used even if no type needs it.
var _ json.RawMessage

// Wire event tags. Use these instead of string literals so vocabulary
// drift is a compile error.
const (
	EventAudioChunk = "audio_chunk"
	EventAudioStart = "audio_start"
	EventAudioStop  = "audio_stop"
)

type AudioChunk struct {
	SessionId   string `json:"session_id"`
	TimestampMs uint64 `json:"timestamp_ms"`
}

type AudioFormat struct {
	Channels uint32 `json:"channels"`
	Rate     uint32 `json:"rate"`
	Width    uint32 `json:"width"`
}

type AudioStart struct {
	Format    AudioFormat `json:"format"`
	SessionId string      `json:"session_id"`
}

type AudioStop struct {
	// Shared-clock position (the AudioChunk `timestamp_ms` timebase) after
	// which buffered audio must NOT be processed. Set when the stop was
	// triggered by something whose audio position is known — a recognized
	// stop phrase, say — so that a consumer buffering ahead of the trigger
	// does not process audio the user never meant to send.
	//
	// A source stage forwards it verbatim on its downstream AudioStop; a
	// batch consumer truncates its buffer at it; absent = process
	// everything.
	CutoffMs  *uint64 `json:"cutoff_ms,omitempty"`
	SessionId string  `json:"session_id"`
}
