// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.
//
// The audio session vocabulary. Import this if your stage produces or
// consumes an audio stream — a speech engine (`speak` in, audio out) and an
// audio sink (audio in, `playback_*` out) included.

package audio

import (
	"encoding/json"
)

// Ensure the json import is used even if no type needs it.
var _ json.RawMessage

// Wire event tags. Use these instead of string literals so vocabulary
// drift is a compile error.
const (
	EventAudioChunk      = "audio_chunk"
	EventAudioStart      = "audio_start"
	EventAudioStop       = "audio_stop"
	EventPlaybackEnded   = "playback_ended"
	EventPlaybackStarted = "playback_started"
	EventSpeak           = "speak"
)

type AudioChunk struct {
	SessionId   string `json:"session_id"`
	TimestampMs uint64 `json:"timestamp_ms"`
}

type AudioFormat struct {
	Channels uint32 `json:"channels"`
	Rate     uint32 `json:"rate"`
	Width    uint32 `json:"width"`
}

type AudioStart struct {
	Format    AudioFormat `json:"format"`
	SessionId string      `json:"session_id"`
}

type AudioStop struct {
	// Shared-clock position (the AudioChunk `timestamp_ms` timebase) after
	// which buffered audio must NOT be processed. Set when the stop was
	// triggered by something whose audio position is known — a recognized
	// stop phrase, say — so that a consumer buffering ahead of the trigger
	// does not process audio the user never meant to send.
	//
	// A source stage forwards it verbatim on its downstream AudioStop; a
	// batch consumer truncates its buffer at it; absent = process
	// everything.
	CutoffMs  *uint64 `json:"cutoff_ms,omitempty"`
	SessionId string  `json:"session_id"`
}

// `playback_ended`: an audio session's last sound left the speakers, or it
// was cut off.
type PlaybackEnded struct {
	// When, on the shared clock (as `playback_started`'s `at_ms`).
	AtMs uint64 `json:"at_ms"`
	// True when playback was stopped before the audio ran out.
	Interrupted *bool  `json:"interrupted,omitempty"`
	SessionId   string `json:"session_id"`
}

// `playback_started`: an audio session's first sound left the speakers.
//
// Emitted by an audio sink (`stage_type` `speaker`) — the stage that plays
// audio rather than processing it — so the platform knows exactly when the
// person, and the microphone, began to hear it.
type PlaybackStarted struct {
	// When, on the shared clock (the `AudioChunk` `timestamp_ms` timebase,
	// which each SDK's stage runtime reads for you). Comparable with the
	// onsets a recognizer
	// reports, which is what lets the platform drop its own voice coming
	// back through the microphone.
	AtMs      uint64 `json:"at_ms"`
	SessionId string `json:"session_id"`
}

// The `speak` request: say these words. Sent by the platform to a speech
// engine (`stage_type` `tts`), one per utterance.
//
// The engine answers on the same `session_id` with the audio session
// vocabulary, run the other way: `audio_start` (its format), `audio_chunk`s
// as it synthesizes — streaming, so the first words play while the rest are
// still being made — and exactly one `audio_stop` when the utterance is
// over, whether it finished, failed (an `error` with this `session_id`
// first) or was cancelled. Every request gets that one `audio_stop`, even
// one cancelled before it started, so the platform never waits on an
// utterance that will not come.
//
// Cancel is an inbound `audio_stop` naming the session: the engine stops
// producing for it at once and closes it. Requests are spoken in the order
// they arrive; which utterance goes first, and what cuts in, is the
// platform's decision, not the engine's.
type Speak struct {
	// BCP 47 tag of the language `text` is in, when the caller knows it. An
	// engine with voices in several languages may use it to pick one when no
	// voice is named.
	Locale *string `json:"locale,omitempty"`
	// Pace relative to the voice's own: 1.0 is normal, 2.0 twice as fast.
	// Absent → 1.0. An engine that cannot change pace speaks at 1.0.
	Rate *float32 `json:"rate,omitempty"`
	// The utterance. Every event the engine sends about it carries this.
	SessionId string `json:"session_id"`
	// The words, plain text without markup, read as written.
	Text string `json:"text"`
	// The `id` of one of the engine's `voices` (its capability). Absent, or
	// not one the engine declared → its default voice (the first declared).
	Voice *string `json:"voice,omitempty"`
}
