// AUTO-GENERATED by emit-sdk — do not edit.
// Run: just contracts

package shared

// InputDirective* are the closed-vocabulary keys plugins may write
// into `_platform.input.directives`. The actuator's state put path
// rejects writes with any other key. Source of truth:
// `actuator/src/state.rs::InputDirectives::KNOWN_KEYS`.
const (
	InputDirectiveLiftKeysOnDispatch = "lift_keys_on_dispatch"
)

// Effect* are the registered effect names plugins may declare in
// `provides.effects`. The actuator's manifest validator rejects
// any other name. Source of truth:
// `actuator/src/effects.rs::EffectDef` inventory entries.
const (
	EffectDisableScreenDim = "disable_screen_dim"
	EffectMuteAudioToOtherApps = "mute_audio_to_other_apps"
	EffectPauseMicrophoneIndicator = "pause_microphone_indicator"
	EffectPreventFocusSteal = "prevent_focus_steal"
	EffectSignalRecordingActive = "signal_recording_active"
	EffectSuppressHuds = "suppress_huds"
	EffectSuppressNotifications = "suppress_notifications"
)

// KnownInputDirectives lists the full closed-vocabulary set of
// `_platform.input.directives` keys. Iterate at startup to
// validate plugin-side constants against the actuator's view.
var KnownInputDirectives = []string{
	"lift_keys_on_dispatch",
}

// KnownEffects lists the full closed-vocabulary set of registered
// effect names.
var KnownEffects = []string{
	"disable_screen_dim",
	"mute_audio_to_other_apps",
	"pause_microphone_indicator",
	"prevent_focus_steal",
	"signal_recording_active",
	"suppress_huds",
	"suppress_notifications",
}
