// AUTO-GENERATED by emit-sdk — do not edit.
// Run: just contracts

package shared

// InputDirective* are the closed-vocabulary keys plugins may write
// into `_platform.input.directives`. The actuator's state put path
// rejects writes with any other key. Source of truth:
// `actuator/src/state.rs::InputDirectives::KNOWN_KEYS`.
const (
	InputDirectiveLiftKeysOnDispatch = "lift_keys_on_dispatch"
)

// Effect* are the registered effect names plugins may declare in
// `provides.effects`. The actuator's manifest validator rejects
// any other name. Source of truth:
// `actuator/src/effects.rs::EffectDef` inventory entries.
const (
	EffectDisableScreenDim         = "disable_screen_dim"
	EffectMuteAudioToOtherApps     = "mute_audio_to_other_apps"
	EffectPauseMicrophoneIndicator = "pause_microphone_indicator"
	EffectPreventFocusSteal        = "prevent_focus_steal"
	EffectSignalRecordingActive    = "signal_recording_active"
	EffectSuppressHuds             = "suppress_huds"
	EffectSuppressKeybinds         = "suppress_keybinds"
	EffectSuppressNotifications    = "suppress_notifications"
)

// KnownInputDirectives lists the full closed-vocabulary set of
// `_platform.input.directives` keys. Iterate at startup to
// validate plugin-side constants against the actuator's view.
var KnownInputDirectives = []string{
	"lift_keys_on_dispatch",
}

// KnownEffects lists the full closed-vocabulary set of registered
// effect names.
var KnownEffects = []string{
	"disable_screen_dim",
	"mute_audio_to_other_apps",
	"pause_microphone_indicator",
	"prevent_focus_steal",
	"signal_recording_active",
	"suppress_huds",
	"suppress_keybinds",
	"suppress_notifications",
}

// ErrorKind* are the closed-vocabulary `kind` values the actuator puts
// in a JSON-RPC error's `data.kind`. Branch on RPCError.Kind rather
// than matching the message prose. Source of truth:
// `actuator/src/fault.rs::ErrorKind`.
//
// An actuator newer than this SDK may send a kind that is not listed
// here; treat an unrecognized value as ErrorKindInternal rather than
// failing to parse.
const (
	ErrorKindNotPermitted      ErrorKind = "not_permitted"
	ErrorKindRecordingDisabled ErrorKind = "recording_disabled"
	ErrorKindNotFound          ErrorKind = "not_found"
	ErrorKindValidation        ErrorKind = "validation"
	ErrorKindForbidden         ErrorKind = "forbidden"
	ErrorKindStorage           ErrorKind = "storage"
	ErrorKindMethodNotFound    ErrorKind = "method_not_found"
	ErrorKindInvalidParams     ErrorKind = "invalid_params"
	ErrorKindInternal          ErrorKind = "internal"
)

// ErrorCodeFor maps a kind to the JSON-RPC error code the actuator
// sends with it. Derived from the kind actuator-side, so the two can
// never disagree on the wire.
var ErrorCodeFor = map[ErrorKind]int{
	ErrorKindNotPermitted:      -32002,
	ErrorKindRecordingDisabled: -32006,
	ErrorKindNotFound:          -32001,
	ErrorKindValidation:        -32004,
	ErrorKindForbidden:         -32003,
	ErrorKindStorage:           -32005,
	ErrorKindMethodNotFound:    -32601,
	ErrorKindInvalidParams:     -32602,
	ErrorKindInternal:          -32603,
}

// KnownErrorKinds lists the full closed-vocabulary set.
var KnownErrorKinds = []ErrorKind{
	ErrorKindNotPermitted,
	ErrorKindRecordingDisabled,
	ErrorKindNotFound,
	ErrorKindValidation,
	ErrorKindForbidden,
	ErrorKindStorage,
	ErrorKindMethodNotFound,
	ErrorKindInvalidParams,
	ErrorKindInternal,
}

// FaultData is the structured payload of a JSON-RPC error's `data`
// member. Only Kind is guaranteed; the rest are populated when they
// apply. Source of truth: `actuator/src/fault.rs::FaultData`.
type FaultData struct {
	Kind       ErrorKind `json:"kind"`
	Collection string    `json:"collection,omitempty"`
	Detail     string    `json:"detail,omitempty"`
	ID         string    `json:"id,omitempty"`
	Op         string    `json:"op,omitempty"`
}
