// AUTO-GENERATED by emit-sdk — do not edit.
// Run: just contracts

package shared

// APIVersion is the BranchKit API version (from contracts/api-version.json).
const APIVersion = "0.1.0"

// RPC method names: plugin → actuator (use with plugin.Call()).
const (
	MethodCollectionDelete = "collection.delete" // since 0.1.0
	MethodCollectionGet = "collection.get" // since 0.1.0
	MethodCollectionPush = "collection.push" // since 0.1.0
	MethodCommandsDiscover = "commands.discover" // since 0.1.0
	MethodCommandsHasPartial = "commands.has_partial" // since 0.1.0
	MethodCommandsList = "commands.list" // since 0.1.0
	MethodCommandsMatch = "commands.match" // since 0.1.0
	MethodCommandsPush = "commands.push" // since 0.1.0
	MethodControlSignal = "control.signal" // since 0.1.0
	MethodDispatch = "dispatch" // since 0.1.0
	MethodEventsAppend = "events.append" // since 0.1.0
	MethodEventsEmit = "events.emit" // since 0.1.0
	MethodHudCreateChannel = "hud.create_channel" // since 0.1.0
	MethodHudHide = "hud.hide" // since 0.1.0
	MethodHudPush = "hud.push" // since 0.1.0
	MethodHudRemoveChannel = "hud.remove_channel" // since 0.1.0
	MethodHudSetSize = "hud.set_size" // since 0.1.0
	MethodHudShow = "hud.show" // since 0.1.0
	MethodInputClick = "input.click" // since 0.1.0
	MethodInputClipboardAction = "input.clipboard_action" // since 0.1.0
	MethodInputClipboardRead = "input.clipboard_read" // since 0.1.0
	MethodInputClipboardReadAll = "input.clipboard_read_all" // since 0.1.0
	MethodInputClipboardWrite = "input.clipboard_write" // since 0.1.0
	MethodInputClipboardWriteItems = "input.clipboard_write_items" // since 0.1.0
	MethodInputDoubleClick = "input.double_click" // since 0.1.0
	MethodInputDrag = "input.drag" // since 0.1.0
	MethodInputListInputSources = "input.list_input_sources" // since 0.1.0
	MethodInputMouseButton = "input.mouse_button" // since 0.1.0
	MethodInputPressKey = "input.press_key" // since 0.1.0
	MethodInputRawKey = "input.raw_key" // since 0.1.0
	MethodInputRightClick = "input.right_click" // since 0.1.0
	MethodInputScroll = "input.scroll" // since 0.1.0
	MethodInputSwitchInputSource = "input.switch_input_source" // since 0.1.0
	MethodInputTypeText = "input.type_text" // since 0.1.0
	MethodKeyNamesSet = "key_names.set" // since 0.1.0
	MethodKeybindsRegister = "keybinds.register" // since 0.1.0
	MethodMatchAliasesGet = "match_aliases.get" // since 0.1.0
	MethodMatchAliasesSet = "match_aliases.set" // since 0.1.0
	MethodNativeActivateApp = "native.activate_app" // since 0.1.0
	MethodNativeActiveSpace = "native.active_space" // since 0.1.0
	MethodNativeAppIcon = "native.app_icon" // since 0.1.0
	MethodNativeAudioDevices = "native.audio_devices" // since 0.1.0
	MethodNativeAxElementAtPoint = "native.ax_element_at_point" // since 0.1.0
	MethodNativeAxElementTree = "native.ax_element_tree" // since 0.1.0
	MethodNativeAxObserve = "native.ax_observe" // since 0.1.0
	MethodNativeAxPerformAction = "native.ax_perform_action" // since 0.1.0
	MethodNativeAxReadAttributes = "native.ax_read_attributes" // since 0.1.0
	MethodNativeAxSetAttribute = "native.ax_set_attribute" // since 0.1.0
	MethodNativeAxUnobserve = "native.ax_unobserve" // since 0.1.0
	MethodNativeBatchIsTileable = "native.batch_is_tileable" // since 0.1.0
	MethodNativeBatchSetFrames = "native.batch_set_frames" // since 0.1.0
	MethodNativeBattery = "native.battery" // since 0.1.0
	MethodNativeBluetoothDevices = "native.bluetooth_devices" // since 0.1.0
	MethodNativeBorders = "native.borders" // since 0.1.0
	MethodNativeBrightness = "native.brightness" // since 0.1.0
	MethodNativeCaptureWindow = "native.capture_window" // since 0.1.0
	MethodNativeClickMenuItem = "native.click_menu_item" // since 0.1.0
	MethodNativeClipboardChangeCount = "native.clipboard_change_count" // since 0.1.0
	MethodNativeCloseWindow = "native.close_window" // since 0.1.0
	MethodNativeColorAtPoint = "native.color_at_point" // since 0.1.0
	MethodNativeCurrentUser = "native.current_user" // since 0.1.0
	MethodNativeCursor = "native.cursor" // since 0.1.0
	MethodNativeCursorInfo = "native.cursor_info" // since 0.1.0
	MethodNativeDarkMode = "native.dark_mode" // since 0.1.0
	MethodNativeDefaultBrowser = "native.default_browser" // since 0.1.0
	MethodNativeDismissNotification = "native.dismiss_notification" // since 0.1.0
	MethodNativeDisplays = "native.displays" // since 0.1.0
	MethodNativeDnd = "native.dnd" // since 0.1.0
	MethodNativeFileTags = "native.file_tags" // since 0.1.0
	MethodNativeForceQuitApp = "native.force_quit_app" // since 0.1.0
	MethodNativeFrontmostApp = "native.frontmost_app" // since 0.1.0
	MethodNativeGetWindowInfo = "native.get_window_info" // since 0.1.0
	MethodNativeHideApp = "native.hide_app" // since 0.1.0
	MethodNativeInstalledApps = "native.installed_apps" // since 0.1.0
	MethodNativeIsAppHidden = "native.is_app_hidden" // since 0.1.0
	MethodNativeKeyboardLayout = "native.keyboard_layout" // since 0.1.0
	MethodNativeLaunchApp = "native.launch_app" // since 0.1.0
	MethodNativeListNotifications = "native.list_notifications" // since 0.1.0
	MethodNativeListSpaces = "native.list_spaces" // since 0.1.0
	MethodNativeLoginItems = "native.login_items" // since 0.1.0
	MethodNativeMenuBar = "native.menu_bar" // since 0.1.0
	MethodNativeMinimizeWindow = "native.minimize_window" // since 0.1.0
	MethodNativeMoveWindowToDisplay = "native.move_window_to_display" // since 0.1.0
	MethodNativeMoveWindowToSpace = "native.move_window_to_space" // since 0.1.0
	MethodNativeMute = "native.mute" // since 0.1.0
	MethodNativeNotify = "native.notify" // since 0.1.0
	MethodNativeObserveWindows = "native.observe_windows" // since 0.1.0
	MethodNativeOpenTarget = "native.open_target" // since 0.1.0
	MethodNativePlaySound = "native.play_sound" // since 0.1.0
	MethodNativePollBurst = "native.poll_burst" // since 0.1.0
	MethodNativePreventSleep = "native.prevent_sleep" // since 0.1.0
	MethodNativeQuickLook = "native.quick_look" // since 0.1.0
	MethodNativeQuitApp = "native.quit_app" // since 0.1.0
	MethodNativeRaiseWindow = "native.raise_window" // since 0.1.0
	MethodNativeRevealInFinder = "native.reveal_in_finder" // since 0.1.0
	MethodNativeRunApplescript = "native.run_applescript" // since 0.1.0
	MethodNativeRunningApps = "native.running_apps" // since 0.1.0
	MethodNativeScreenLock = "native.screen_lock" // since 0.1.0
	MethodNativeScreenshot = "native.screenshot" // since 0.1.0
	MethodNativeSelectedFinderItems = "native.selected_finder_items" // since 0.1.0
	MethodNativeSetAudioDevice = "native.set_audio_device" // since 0.1.0
	MethodNativeSetBrightness = "native.set_brightness" // since 0.1.0
	MethodNativeSetDarkMode = "native.set_dark_mode" // since 0.1.0
	MethodNativeSetDnd = "native.set_dnd" // since 0.1.0
	MethodNativeSetVolume = "native.set_volume" // since 0.1.0
	MethodNativeSetWindowAlpha = "native.set_window_alpha" // since 0.1.0
	MethodNativeSetWindowLevel = "native.set_window_level" // since 0.1.0
	MethodNativeSpeak = "native.speak" // since 0.1.0
	MethodNativeSpotlight = "native.spotlight" // since 0.1.0
	MethodNativeSystemUptime = "native.system_uptime" // since 0.1.0
	MethodNativeToggleFullscreen = "native.toggle_fullscreen" // since 0.1.0
	MethodNativeTrash = "native.trash" // since 0.1.0
	MethodNativeUnhideApp = "native.unhide_app" // since 0.1.0
	MethodNativeUnminimizeWindow = "native.unminimize_window" // since 0.1.0
	MethodNativeUnobserveWindows = "native.unobserve_windows" // since 0.1.0
	MethodNativeVolume = "native.volume" // since 0.1.0
	MethodNativeWarpCursor = "native.warp_cursor" // since 0.1.0
	MethodNativeWifi = "native.wifi" // since 0.1.0
	MethodNativeWorldModel = "native.world_model" // since 0.1.0
	MethodSelectionPick = "selection.pick" // since 0.1.0
	MethodSelectionSet = "selection.set" // since 0.1.0
	MethodSessionEndCleanup = "session.end_cleanup" // since 0.1.0
	MethodSettingsRulesCreate = "settings.rules_create" // since 0.1.0
	MethodSettingsRulesUpdate = "settings.rules_update" // since 0.1.0
	MethodSystemLaunchApp = "system.launch_app" // since 0.1.0
	MethodSystemNotify = "system.notify" // since 0.1.0
	MethodSystemRunShell = "system.run_shell" // since 0.1.0
	MethodTagsGet = "tags.get" // since 0.1.0
	MethodTagsModify = "tags.modify" // since 0.1.0
)

// RPC method names: actuator → plugin (use with plugin.Handle()).
const (
	HookOnAction = "on_action" // since 0.1.0
	HookOnCommandsChanged = "on_commands_changed" // since 0.1.0
	HookRenderHud = "render_hud" // since 0.1.0
	HookRenderSettings = "render_settings" // since 0.1.0
	HookSpeechPipelineFull = "speech_pipeline_full" // since 0.1.0
)

// Platform event type constants (use with plugin.On()).
const (
	EventActionExecuted = "_platform.action.executed"
	EventAppFocused = "_platform.app.focused"
	EventCollectionUpdated = "_platform.collection.updated"
	EventDisplayChanged = "_platform.display.changed"
	EventInputSessionEnded = "_platform.input.session_ended"
	EventKeyboardLayoutChanged = "_platform.keyboard.layout_changed"
	EventPluginDegraded = "_platform.plugin.degraded"
	EventPluginDisabled = "_platform.plugin.disabled"
	EventPluginEnabled = "_platform.plugin.enabled"
	EventSelectionPicked = "_platform.selection.picked"
	EventTagsChanged = "_platform.tags.changed"
	EventWindowClosed = "_platform.window.closed"
	EventWindowCreated = "_platform.window.created"
	EventWindowFocused = "_platform.window.focused"
	EventWindowFrameChanged = "_platform.window.frame_changed"
	EventWindowTitleChanged = "_platform.window.title_changed"
	EventWorkspaceChanged = "_platform.workspace.changed"
	EventWorldUpdated = "_platform.world.updated"
)

// Tag namespace prefix and value constants.
const (
	TagPrefixApp = "app."
	TagPrefixPlugin = "plugin."
	TagInputActive = "_platform.input.active"
	TagInputLiftKeys = "_platform.input.lift_keys"
)
