// AUTO-GENERATED by emit-sdk — do not edit.
// Run: just contracts

package shared

import "encoding/json"

// Ensure json import is used.
var _ json.RawMessage

// CollectionDelete delete a dynamic collection.
func (p *Plugin) CollectionDelete(name string) error {
	req := &CollectionDeleteRequest{
		Name: name,
	}
	return p.Call(MethodCollectionDelete, req, nil)
}

// CollectionGet read collection data with optional merge metadata.
func (p *Plugin) CollectionGet(name string) (*CollectionGetResponse, error) {
	req := &CollectionGetRequest{
		Name: name,
	}
	var result CollectionGetResponse
	err := p.Call(MethodCollectionGet, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CollectionOverride add, remove, restore, patch, or reset user overrides for a collection.
func (p *Plugin) CollectionOverride(action string, collection string, fields json.RawMessage, id json.RawMessage) error {
	req := &CollectionOverrideRequest{
		Action: action,
		Collection: collection,
		Fields: fields,
		ID: id,
	}
	return p.Call(MethodCollectionOverride, req, nil)
}

// CollectionPush write data to a shared store.
func (p *Plugin) CollectionPush(data json.RawMessage, label json.RawMessage, name string) error {
	req := &CollectionPushRequest{
		Data: data,
		Label: label,
		Name: name,
	}
	return p.Call(MethodCollectionPush, req, nil)
}

// CollectionsList list collections with entries for display, optionally filtered by kind.
func (p *Plugin) CollectionsList(kind json.RawMessage) ([]CollectionsListSection, error) {
	req := &CollectionsListRequest{
		Kind: kind,
	}
	var result struct {
		Sections []CollectionsListSection `json:"sections"`
	}
	err := p.Call(MethodCollectionsList, req, &result)
	if err != nil {
		return nil, err
	}
	return result.Sections, nil
}

// CommandsDiscover discover available commands or next tokens for a partial match.
func (p *Plugin) CommandsDiscover(activeTags json.RawMessage, requireTag json.RawMessage, words json.RawMessage) (*CommandsDiscoverResponse, error) {
	req := &CommandsDiscoverRequest{
		ActiveTags: activeTags,
		RequireTag: requireTag,
		Words: words,
	}
	var result CommandsDiscoverResponse
	err := p.Call(MethodCommandsDiscover, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CommandsHasPartial check if words partially match any command (prefix matching).
func (p *Plugin) CommandsHasPartial(activeTags json.RawMessage, words []string) (*CommandsHasPartialResponse, error) {
	req := &CommandsHasPartialRequest{
		ActiveTags: activeTags,
		Words: words,
	}
	var result CommandsHasPartialResponse
	err := p.Call(MethodCommandsHasPartial, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CommandsList return all commands grouped by category for HUD display.
func (p *Plugin) CommandsList() (*CommandsListResponse, error) {
	var result CommandsListResponse
	err := p.Call(MethodCommandsList, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CommandsMatch match words against the command registry.
func (p *Plugin) CommandsMatch(activeTags json.RawMessage, words []string) (*CommandsMatchResponse, error) {
	req := &CommandsMatchRequest{
		ActiveTags: activeTags,
		Words: words,
	}
	var result CommandsMatchResponse
	err := p.Call(MethodCommandsMatch, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CommandsPush register commands with the matching engine to the matching engine.
func (p *Plugin) CommandsPush(commands json.RawMessage) (*CommandsPushResponse, error) {
	req := &CommandsPushRequest{
		Commands: commands,
	}
	var result CommandsPushResponse
	err := p.Call(MethodCommandsPush, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ControlSignal send a control signal to the Swift shell via the control stream.
func (p *Plugin) ControlSignal(signal string) error {
	req := &ControlSignalRequest{
		Signal: signal,
	}
	return p.Call(MethodControlSignal, req, nil)
}

// Dispatch dispatch a typed Action to a plugin or platform builtin.
func (p *Plugin) Dispatch(action json.RawMessage) (*DispatchResponse, error) {
	req := &DispatchRequest{
		Action: action,
	}
	var result DispatchResponse
	err := p.Call(MethodDispatch, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// EventsAppend append an event to the structured event log.
func (p *Plugin) EventsAppend(data json.RawMessage, eventType string, sessionID *string) error {
	req := &EventsAppendRequest{
		Data: data,
		EventType: eventType,
		SessionID: sessionID,
	}
	return p.Call(MethodEventsAppend, req, nil)
}

// EventsEmit emit a plugin event on the event bus.
func (p *Plugin) EventsEmit(correlationID json.RawMessage, data json.RawMessage, eventType string) error {
	req := &EventsEmitRequest{
		CorrelationID: correlationID,
		Data: data,
		EventType: eventType,
	}
	return p.Call(MethodEventsEmit, req, nil)
}

// HUDCreateChannel create a new HUD broadcast channel at runtime.
func (p *Plugin) HUDCreateChannel(acceptsInput *bool, anchor json.RawMessage, channel string, description *string, followsFocus *bool, minHeight *int, width *int) error {
	req := &HUDCreateChannelRequest{
		AcceptsInput: acceptsInput,
		Anchor: anchor,
		Channel: channel,
		Description: description,
		FollowsFocus: followsFocus,
		MinHeight: minHeight,
		Width: width,
	}
	return p.Call(MethodHudCreateChannel, req, nil)
}

// HUDHide hide a HUD channel's window.
func (p *Plugin) HUDHide(channel string) error {
	req := &HUDHideRequest{
		Channel: channel,
	}
	return p.Call(MethodHudHide, req, nil)
}

// HUDPush push HTML fragments to a named HUD channel.
func (p *Plugin) HUDPush(channel string, fragments json.RawMessage) error {
	req := &HUDPushRequest{
		Channel: channel,
		Fragments: fragments,
	}
	return p.Call(MethodHudPush, req, nil)
}

// HUDRemoveChannel remove a HUD broadcast channel.
func (p *Plugin) HUDRemoveChannel(channel string) (*HUDRemoveChannelResponse, error) {
	req := &HUDRemoveChannelRequest{
		Channel: channel,
	}
	var result HUDRemoveChannelResponse
	err := p.Call(MethodHudRemoveChannel, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// HUDSetSize report actual rendered size for a HUD channel window.
func (p *Plugin) HUDSetSize(channel string, height int) error {
	req := &HUDSetSizeRequest{
		Channel: channel,
		Height: height,
	}
	return p.Call(MethodHudSetSize, req, nil)
}

// HUDShow show a HUD channel's window.
func (p *Plugin) HUDShow(channel string) error {
	req := &HUDShowRequest{
		Channel: channel,
	}
	return p.Call(MethodHudShow, req, nil)
}

// InputClick click a mouse button.
func (p *Plugin) InputClick(button *string) error {
	req := &InputClickRequest{
		Button: button,
	}
	return p.Call(MethodInputClick, req, nil)
}

// InputClipboardAction perform a clipboard action (copy, paste, or set text).
func (p *Plugin) InputClipboardAction(action string, text json.RawMessage) error {
	req := &InputClipboardActionRequest{
		Action: action,
		Text: text,
	}
	return p.Call(MethodInputClipboardAction, req, nil)
}

// InputClipboardRead read clipboard contents by type.
func (p *Plugin) InputClipboardRead(contentType string) (*InputClipboardReadResponse, error) {
	req := &InputClipboardReadRequest{
		ContentType: contentType,
	}
	var result InputClipboardReadResponse
	err := p.Call(MethodInputClipboardRead, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// InputClipboardReadAll read all items from the clipboard.
func (p *Plugin) InputClipboardReadAll() ([]ClipboardContents, error) {
	var result struct {
		Items []ClipboardContents `json:"items"`
	}
	err := p.Call(MethodInputClipboardReadAll, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Items, nil
}

// InputClipboardWrite write typed content to clipboard.
func (p *Plugin) InputClipboardWrite(contentType string, data string) error {
	req := &InputClipboardWriteRequest{
		ContentType: contentType,
		Data: data,
	}
	return p.Call(MethodInputClipboardWrite, req, nil)
}

// InputClipboardWriteItems write multiple typed items to the clipboard.
func (p *Plugin) InputClipboardWriteItems(items []ClipboardWriteItem) error {
	req := &InputClipboardWriteItemsRequest{
		Items: items,
	}
	return p.Call(MethodInputClipboardWriteItems, req, nil)
}

// InputDoubleClick double-click at position.
func (p *Plugin) InputDoubleClick(x json.RawMessage, y json.RawMessage) error {
	req := &InputDoubleClickRequest{
		X: x,
		Y: y,
	}
	return p.Call(MethodInputDoubleClick, req, nil)
}

// InputDrag atomic drag: mouse down, move, mouse up.
func (p *Plugin) InputDrag(durationMs *int, fromX int, fromY int, toX int, toY int) error {
	req := &InputDragRequest{
		DurationMs: durationMs,
		FromX: fromX,
		FromY: fromY,
		ToX: toX,
		ToY: toY,
	}
	return p.Call(MethodInputDrag, req, nil)
}

// InputListInputSources list available keyboard input sources.
func (p *Plugin) InputListInputSources() ([]InputSource, error) {
	var result struct {
		Sources []InputSource `json:"sources"`
	}
	err := p.Call(MethodInputListInputSources, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Sources, nil
}

// InputMouseButton press or release a mouse button (for drag operations, etc.).
func (p *Plugin) InputMouseButton(button *string, direction string) error {
	req := &InputMouseButtonRequest{
		Button: button,
		Direction: direction,
	}
	return p.Call(MethodInputMouseButton, req, nil)
}

// InputPressKey press a key by raw keycode or name, with optional modifiers.
func (p *Plugin) InputPressKey(code json.RawMessage, modifiers []string, name json.RawMessage) error {
	req := &InputPressKeyRequest{
		Code: code,
		Modifiers: modifiers,
		Name: name,
	}
	return p.Call(MethodInputPressKey, req, nil)
}

// InputRawKey send a raw key event (press, release, or click) without modifier lifting.
func (p *Plugin) InputRawKey(code int, direction string) error {
	req := &InputRawKeyRequest{
		Code: code,
		Direction: direction,
	}
	return p.Call(MethodInputRawKey, req, nil)
}

// InputRightClick right-click at position.
func (p *Plugin) InputRightClick(x json.RawMessage, y json.RawMessage) error {
	req := &InputRightClickRequest{
		X: x,
		Y: y,
	}
	return p.Call(MethodInputRightClick, req, nil)
}

// InputScroll scroll the mouse wheel.
func (p *Plugin) InputScroll(amount *int, direction string) error {
	req := &InputScrollRequest{
		Amount: amount,
		Direction: direction,
	}
	return p.Call(MethodInputScroll, req, nil)
}

// InputSwitchInputSource switch keyboard input source.
func (p *Plugin) InputSwitchInputSource(sourceID string) (bool, error) {
	req := &InputSwitchInputSourceRequest{
		SourceID: sourceID,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodInputSwitchInputSource, req, &result)
	return result.Result, err
}

// InputTypeText type text into the active application via clipboard paste.
func (p *Plugin) InputTypeText(text string) error {
	req := &InputTypeTextRequest{
		Text: text,
	}
	return p.Call(MethodInputTypeText, req, nil)
}

// KeyNamesSet set the key name → keycode mapping for keyboard input simulation.
func (p *Plugin) KeyNamesSet(names map[string]int) (*KeyNamesSetResponse, error) {
	req := &KeyNamesSetRequest{
		Names: names,
	}
	var result KeyNamesSetResponse
	err := p.Call(MethodKeyNamesSet, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// KeybindsRegister register keybind snapshot with the platform (caches and sends to Swift shell).
func (p *Plugin) KeybindsRegister(snapshot json.RawMessage) (*KeybindsRegisterResponse, error) {
	req := &KeybindsRegisterRequest{
		Snapshot: snapshot,
	}
	var result KeybindsRegisterResponse
	err := p.Call(MethodKeybindsRegister, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// MatchAliasesGet get all registered match aliases.
func (p *Plugin) MatchAliasesGet() (*MatchAliasesGetResponse, error) {
	var result MatchAliasesGetResponse
	err := p.Call(MethodMatchAliasesGet, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// MatchAliasesSet register word aliases for command matching (e.g., 'three' → '3'). Aliases are merged with existing entries..
func (p *Plugin) MatchAliasesSet(aliases map[string]string) (*MatchAliasesSetResponse, error) {
	req := &MatchAliasesSetRequest{
		Aliases: aliases,
	}
	var result MatchAliasesSetResponse
	err := p.Call(MethodMatchAliasesSet, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeActivateApp bring an app to front by bundle ID.
func (p *Plugin) NativeActivateApp(allWindows *bool, bundleID string) error {
	req := &NativeActivateAppRequest{
		AllWindows: allWindows,
		BundleID: bundleID,
	}
	return p.Call(MethodNativeActivateApp, req, nil)
}

// NativeActiveSpace get the active space per display.
func (p *Plugin) NativeActiveSpace() ([]ActiveSpace, error) {
	var result struct {
		Active []ActiveSpace `json:"active"`
	}
	err := p.Call(MethodNativeActiveSpace, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Active, nil
}

// NativeAppIcon get app icon as PNG (base64).
func (p *Plugin) NativeAppIcon(bundleID string, size *int) (*NativeAppIconResponse, error) {
	req := &NativeAppIconRequest{
		BundleID: bundleID,
		Size: size,
	}
	var result NativeAppIconResponse
	err := p.Call(MethodNativeAppIcon, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeAudioDevices list all audio input and output devices.
func (p *Plugin) NativeAudioDevices() ([]AudioDevice, error) {
	var result struct {
		Devices []AudioDevice `json:"devices"`
	}
	err := p.Call(MethodNativeAudioDevices, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Devices, nil
}

// NativeAxElementAtPoint get the accessibility element at a screen point.
func (p *Plugin) NativeAxElementAtPoint(pid int, x int, y int) (*NativeAxElementAtPointResponse, error) {
	req := &NativeAxElementAtPointRequest{
		Pid: pid,
		X: x,
		Y: y,
	}
	var result NativeAxElementAtPointResponse
	err := p.Call(MethodNativeAxElementAtPoint, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeAxElementTree get the accessibility element tree rooted at an element.
func (p *Plugin) NativeAxElementTree(depth *int, element AXElementRef) (*AXElementNode, error) {
	req := &NativeAxElementTreeRequest{
		Depth: depth,
		Element: element,
	}
	var result AXElementNode
	err := p.Call(MethodNativeAxElementTree, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeAxObserve start observing AX notifications (STUB — not yet implemented).
func (p *Plugin) NativeAxObserve(notifications []string, pid int) (*NativeAxObserveResponse, error) {
	req := &NativeAxObserveRequest{
		Notifications: notifications,
		Pid: pid,
	}
	var result NativeAxObserveResponse
	err := p.Call(MethodNativeAxObserve, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeAxPerformAction perform an action on an accessibility element.
func (p *Plugin) NativeAxPerformAction(action string, element AXElementRef) (bool, error) {
	req := &NativeAxPerformActionRequest{
		Action: action,
		Element: element,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodNativeAxPerformAction, req, &result)
	return result.Result, err
}

// NativeAxReadAttributes read specific attributes from an accessibility element.
func (p *Plugin) NativeAxReadAttributes(attributes []string, element AXElementRef) error {
	req := &NativeAxReadAttributesRequest{
		Attributes: attributes,
		Element: element,
	}
	return p.Call(MethodNativeAxReadAttributes, req, nil)
}

// NativeAxSetAttribute set an attribute on an accessibility element.
func (p *Plugin) NativeAxSetAttribute(attribute string, element AXElementRef, value json.RawMessage) (bool, error) {
	req := &NativeAxSetAttributeRequest{
		Attribute: attribute,
		Element: element,
		Value: value,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodNativeAxSetAttribute, req, &result)
	return result.Result, err
}

// NativeAxUnobserve stop observing AX notifications (STUB).
func (p *Plugin) NativeAxUnobserve(subscriptionID string) (bool, error) {
	req := &NativeAxUnobserveRequest{
		SubscriptionID: subscriptionID,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodNativeAxUnobserve, req, &result)
	return result.Result, err
}

// NativeBatchIsTileable check which windows can be tiled.
func (p *Plugin) NativeBatchIsTileable(windowIds []string) ([]TileableEntry, error) {
	req := &NativeBatchIsTileableRequest{
		WindowIds: windowIds,
	}
	var result struct {
		Results []TileableEntry `json:"results"`
	}
	err := p.Call(MethodNativeBatchIsTileable, req, &result)
	if err != nil {
		return nil, err
	}
	return result.Results, nil
}

// NativeBatchSetFrames set positions/sizes for multiple windows.
func (p *Plugin) NativeBatchSetFrames(frames []WindowFrame, readback *bool) ([]WindowFrame, error) {
	req := &NativeBatchSetFramesRequest{
		Frames: frames,
		Readback: readback,
	}
	var result struct {
		Results []WindowFrame `json:"results"`
	}
	err := p.Call(MethodNativeBatchSetFrames, req, &result)
	if err != nil {
		return nil, err
	}
	return result.Results, nil
}

// NativeBattery get battery status information.
func (p *Plugin) NativeBattery() (*NativeBatteryResponse, error) {
	var result NativeBatteryResponse
	err := p.Call(MethodNativeBattery, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeBleDiscoverServices discover GATT services and characteristics on a paired BLE device.
func (p *Plugin) NativeBleDiscoverServices(deviceIdentifier string) ([]BleService, error) {
	req := &NativeBleDiscoverServicesRequest{
		DeviceIdentifier: deviceIdentifier,
	}
	var result struct {
		Services []BleService `json:"services"`
	}
	err := p.Call(MethodNativeBleDiscoverServices, req, &result)
	if err != nil {
		return nil, err
	}
	return result.Services, nil
}

// NativeBleSubscribe subscribe to GATT notifications on a BLE characteristic.
func (p *Plugin) NativeBleSubscribe(characteristicUuid string, deviceIdentifier string, serviceUuid string) (*NativeBleSubscribeResponse, error) {
	req := &NativeBleSubscribeRequest{
		CharacteristicUuid: characteristicUuid,
		DeviceIdentifier: deviceIdentifier,
		ServiceUuid: serviceUuid,
	}
	var result NativeBleSubscribeResponse
	err := p.Call(MethodNativeBleSubscribe, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeBleSubscribeAllThenWrite subscribe to all notify characteristics on listed services, then write — single GATT cycle.
func (p *Plugin) NativeBleSubscribeAllThenWrite(deviceIdentifier string, subscribeServices []string, writes []BleWriteEntry) (*NativeBleSubscribeAllThenWriteResponse, error) {
	req := &NativeBleSubscribeAllThenWriteRequest{
		DeviceIdentifier: deviceIdentifier,
		SubscribeServices: subscribeServices,
		Writes: writes,
	}
	var result NativeBleSubscribeAllThenWriteResponse
	err := p.Call(MethodNativeBleSubscribeAllThenWrite, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeBleWrite write bytes to a GATT characteristic on a paired BLE device.
func (p *Plugin) NativeBleWrite(characteristicUuid string, data []int, deviceIdentifier string, serviceUuid string, writeType *string) (*NativeBleWriteResponse, error) {
	req := &NativeBleWriteRequest{
		CharacteristicUuid: characteristicUuid,
		Data: data,
		DeviceIdentifier: deviceIdentifier,
		ServiceUuid: serviceUuid,
		WriteType: writeType,
	}
	var result NativeBleWriteResponse
	err := p.Call(MethodNativeBleWrite, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeBluetoothDevices list paired/connected Bluetooth devices.
func (p *Plugin) NativeBluetoothDevices() ([]BluetoothDevice, error) {
	var result struct {
		Devices []BluetoothDevice `json:"devices"`
	}
	err := p.Call(MethodNativeBluetoothDevices, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Devices, nil
}

// NativeBorders draw window border overlays (forwarded to Swift shell).
func (p *Plugin) NativeBorders() error {
	return p.Call(MethodNativeBorders, nil, nil)
}

// NativeBrightness get display brightness (0.0-1.0).
func (p *Plugin) NativeBrightness(displayID json.RawMessage) (*NativeBrightnessResponse, error) {
	req := &NativeBrightnessRequest{
		DisplayID: displayID,
	}
	var result NativeBrightnessResponse
	err := p.Call(MethodNativeBrightness, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeCaptureWindow capture a single window as PNG (base64).
func (p *Plugin) NativeCaptureWindow(windowID string) (*NativeCaptureWindowResponse, error) {
	req := &NativeCaptureWindowRequest{
		WindowID: windowID,
	}
	var result NativeCaptureWindowResponse
	err := p.Call(MethodNativeCaptureWindow, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeClickMenuItem click a menu item by navigating the menu bar path.
func (p *Plugin) NativeClickMenuItem(path []string, pid int) (bool, error) {
	req := &NativeClickMenuItemRequest{
		Path: path,
		Pid: pid,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodNativeClickMenuItem, req, &result)
	return result.Result, err
}

// NativeClipboardChangeCount get the clipboard change count.
func (p *Plugin) NativeClipboardChangeCount() (*NativeClipboardChangeCountResponse, error) {
	var result NativeClipboardChangeCountResponse
	err := p.Call(MethodNativeClipboardChangeCount, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeCloseWindow close a window by ID.
func (p *Plugin) NativeCloseWindow(windowID string) error {
	req := &NativeCloseWindowRequest{
		WindowID: windowID,
	}
	return p.Call(MethodNativeCloseWindow, req, nil)
}

// NativeColorAtPoint sample pixel color at screen coordinate.
func (p *Plugin) NativeColorAtPoint(x int, y int) (*NativeColorAtPointResponse, error) {
	req := &NativeColorAtPointRequest{
		X: x,
		Y: y,
	}
	var result NativeColorAtPointResponse
	err := p.Call(MethodNativeColorAtPoint, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeCurrentUser get current user session info.
func (p *Plugin) NativeCurrentUser() (*NativeCurrentUserResponse, error) {
	var result NativeCurrentUserResponse
	err := p.Call(MethodNativeCurrentUser, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeCursor get the current cursor position.
func (p *Plugin) NativeCursor() (*NativeCursorResponse, error) {
	var result NativeCursorResponse
	err := p.Call(MethodNativeCursor, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeCursorInfo get current cursor type and position.
func (p *Plugin) NativeCursorInfo() (*NativeCursorInfoResponse, error) {
	var result NativeCursorInfoResponse
	err := p.Call(MethodNativeCursorInfo, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeDarkMode check if dark mode is active.
func (p *Plugin) NativeDarkMode() (*NativeDarkModeResponse, error) {
	var result NativeDarkModeResponse
	err := p.Call(MethodNativeDarkMode, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeDefaultBrowser get the default browser bundle ID.
func (p *Plugin) NativeDefaultBrowser() (*NativeDefaultBrowserResponse, error) {
	var result NativeDefaultBrowserResponse
	err := p.Call(MethodNativeDefaultBrowser, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeDismissNotification dismiss a delivered notification (partial — no-op).
func (p *Plugin) NativeDismissNotification(id string) error {
	req := &NativeDismissNotificationRequest{
		ID: id,
	}
	return p.Call(MethodNativeDismissNotification, req, nil)
}

// NativeDisplays get metadata for all connected displays.
func (p *Plugin) NativeDisplays() ([]DisplayMetadata, error) {
	var result struct {
		Displays []DisplayMetadata `json:"displays"`
	}
	err := p.Call(MethodNativeDisplays, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Displays, nil
}

// NativeDnd get Do Not Disturb / Focus state.
func (p *Plugin) NativeDnd() (*NativeDndResponse, error) {
	var result NativeDndResponse
	err := p.Call(MethodNativeDnd, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeFileTags read or write Finder tags on a file.
func (p *Plugin) NativeFileTags(path string, tags json.RawMessage) error {
	req := &NativeFileTagsRequest{
		Path: path,
		Tags: tags,
	}
	return p.Call(MethodNativeFileTags, req, nil)
}

// NativeForceQuitApp force-quit an app by bundle ID.
func (p *Plugin) NativeForceQuitApp(bundleID string) (bool, error) {
	req := &NativeForceQuitAppRequest{
		BundleID: bundleID,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodNativeForceQuitApp, req, &result)
	return result.Result, err
}

// NativeFrontmostApp get the currently active (frontmost) application.
func (p *Plugin) NativeFrontmostApp() (*NativeFrontmostAppResponse, error) {
	var result NativeFrontmostAppResponse
	err := p.Call(MethodNativeFrontmostApp, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeGetWindowInfo get detailed info for a single window.
func (p *Plugin) NativeGetWindowInfo(windowID string) (*NativeGetWindowInfoResponse, error) {
	req := &NativeGetWindowInfoRequest{
		WindowID: windowID,
	}
	var result NativeGetWindowInfoResponse
	err := p.Call(MethodNativeGetWindowInfo, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeHidClaim seize exclusive access to a HID device, suppressing native macOS events.
func (p *Plugin) NativeHidClaim(deviceID string) (*NativeHidClaimResponse, error) {
	req := &NativeHidClaimRequest{
		DeviceID: deviceID,
	}
	var result NativeHidClaimResponse
	err := p.Call(MethodNativeHidClaim, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeHidDevices list all connected non-Apple HID devices.
func (p *Plugin) NativeHidDevices() ([]HidDeviceEntry, error) {
	var result struct {
		Devices []HidDeviceEntry `json:"devices"`
	}
	err := p.Call(MethodNativeHidDevices, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Devices, nil
}

// NativeHidElements return the parsed HID element tree (buttons, axes, dials) for a connected device.
func (p *Plugin) NativeHidElements(deviceID string) ([]HidElementEntry, error) {
	req := &NativeHidElementsRequest{
		DeviceID: deviceID,
	}
	var result struct {
		Elements []HidElementEntry `json:"elements"`
	}
	err := p.Call(MethodNativeHidElements, req, &result)
	if err != nil {
		return nil, err
	}
	return result.Elements, nil
}

// NativeHidRelease release exclusive access to a HID device, restoring native macOS behavior.
func (p *Plugin) NativeHidRelease(deviceID string) (*NativeHidReleaseResponse, error) {
	req := &NativeHidReleaseRequest{
		DeviceID: deviceID,
	}
	var result NativeHidReleaseResponse
	err := p.Call(MethodNativeHidRelease, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeHidSendReport send an output or feature report to a connected HID device.
func (p *Plugin) NativeHidSendReport(data []int, deviceID string, reportID int, reportType string) (*NativeHidSendReportResponse, error) {
	req := &NativeHidSendReportRequest{
		Data: data,
		DeviceID: deviceID,
		ReportID: reportID,
		ReportType: reportType,
	}
	var result NativeHidSendReportResponse
	err := p.Call(MethodNativeHidSendReport, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeHideApp hide an app by bundle ID.
func (p *Plugin) NativeHideApp(bundleID string) error {
	req := &NativeHideAppRequest{
		BundleID: bundleID,
	}
	return p.Call(MethodNativeHideApp, req, nil)
}

// NativeInstalledApps list all installed applications by scanning the filesystem.
func (p *Plugin) NativeInstalledApps() ([]InstalledApp, error) {
	var result struct {
		Apps []InstalledApp `json:"apps"`
	}
	err := p.Call(MethodNativeInstalledApps, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Apps, nil
}

// NativeIsAppHidden check if an application is hidden.
func (p *Plugin) NativeIsAppHidden(bundleID string) (bool, error) {
	req := &NativeIsAppHiddenRequest{
		BundleID: bundleID,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodNativeIsAppHidden, req, &result)
	return result.Result, err
}

// NativeKeyboardLayout get the current keyboard layout and key mappings.
func (p *Plugin) NativeKeyboardLayout() (*NativeKeyboardLayoutResponse, error) {
	var result NativeKeyboardLayoutResponse
	err := p.Call(MethodNativeKeyboardLayout, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeLaunchApp launch an application by bundle ID.
func (p *Plugin) NativeLaunchApp(bundleID string, newInstance *bool) error {
	req := &NativeLaunchAppRequest{
		BundleID: bundleID,
		NewInstance: newInstance,
	}
	return p.Call(MethodNativeLaunchApp, req, nil)
}

// NativeListNotifications list delivered notifications (partial — returns empty).
func (p *Plugin) NativeListNotifications() ([]DeliveredNotification, error) {
	var result struct {
		Notifications []DeliveredNotification `json:"notifications"`
	}
	err := p.Call(MethodNativeListNotifications, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Notifications, nil
}

// NativeListSpaces list all spaces across all displays.
func (p *Plugin) NativeListSpaces() ([]SpaceInfo, error) {
	var result struct {
		Spaces []SpaceInfo `json:"spaces"`
	}
	err := p.Call(MethodNativeListSpaces, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Spaces, nil
}

// NativeLoginItems list login items (launch-at-login entries).
func (p *Plugin) NativeLoginItems() ([]LoginItem, error) {
	var result struct {
		Items []LoginItem `json:"items"`
	}
	err := p.Call(MethodNativeLoginItems, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Items, nil
}

// NativeMenuBar read the menu bar structure of an application by PID.
func (p *Plugin) NativeMenuBar(pid int) ([]MenuItem, error) {
	req := &NativeMenuBarRequest{
		Pid: pid,
	}
	var result struct {
		Items []MenuItem `json:"items"`
	}
	err := p.Call(MethodNativeMenuBar, req, &result)
	if err != nil {
		return nil, err
	}
	return result.Items, nil
}

// NativeMinimizeWindow minimize a window by ID.
func (p *Plugin) NativeMinimizeWindow(windowID string) error {
	req := &NativeMinimizeWindowRequest{
		WindowID: windowID,
	}
	return p.Call(MethodNativeMinimizeWindow, req, nil)
}

// NativeMoveWindowToDisplay move a window to a different display.
func (p *Plugin) NativeMoveWindowToDisplay(displayID int, windowID string) error {
	req := &NativeMoveWindowToDisplayRequest{
		DisplayID: displayID,
		WindowID: windowID,
	}
	return p.Call(MethodNativeMoveWindowToDisplay, req, nil)
}

// NativeMoveWindowToSpace move a window to a specific space.
func (p *Plugin) NativeMoveWindowToSpace(spaceID int, windowID string) (bool, error) {
	req := &NativeMoveWindowToSpaceRequest{
		SpaceID: spaceID,
		WindowID: windowID,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodNativeMoveWindowToSpace, req, &result)
	return result.Result, err
}

// NativeMute set mute state on default output device.
func (p *Plugin) NativeMute(muted bool) error {
	req := &NativeMuteRequest{
		Muted: muted,
	}
	return p.Call(MethodNativeMute, req, nil)
}

// NativeNotify post a rich notification (osascript fallback).
func (p *Plugin) NativeNotify(body json.RawMessage, sound json.RawMessage, subtitle json.RawMessage, title string) (*NativeNotifyResponse, error) {
	req := &NativeNotifyRequest{
		Body: body,
		Sound: sound,
		Subtitle: subtitle,
		Title: title,
	}
	var result NativeNotifyResponse
	err := p.Call(MethodNativeNotify, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeObserveWindows start observing window events for a PID (STUB — not yet implemented).
func (p *Plugin) NativeObserveWindows(pid int) (*NativeObserveWindowsResponse, error) {
	req := &NativeObserveWindowsRequest{
		Pid: pid,
	}
	var result NativeObserveWindowsResponse
	err := p.Call(MethodNativeObserveWindows, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeOpenTarget open a URL or file path with the default handler.
func (p *Plugin) NativeOpenTarget(target string) error {
	req := &NativeOpenTargetRequest{
		Target: target,
	}
	return p.Call(MethodNativeOpenTarget, req, nil)
}

// NativePlaySound play a named system sound.
func (p *Plugin) NativePlaySound(name string) error {
	req := &NativePlaySoundRequest{
		Name: name,
	}
	return p.Call(MethodNativePlaySound, req, nil)
}

// NativePollBurst request burst-mode world model polling (200ms intervals).
func (p *Plugin) NativePollBurst() error {
	return p.Call(MethodNativePollBurst, nil, nil)
}

// NativePreventSleep assert or release sleep prevention.
func (p *Plugin) NativePreventSleep(assertionID json.RawMessage, reason *string) (*NativePreventSleepResponse, error) {
	req := &NativePreventSleepRequest{
		AssertionID: assertionID,
		Reason: reason,
	}
	var result NativePreventSleepResponse
	err := p.Call(MethodNativePreventSleep, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeQuickLook generate Quick Look thumbnail as PNG (base64).
func (p *Plugin) NativeQuickLook(path string, size *int) (*NativeQuickLookResponse, error) {
	req := &NativeQuickLookRequest{
		Path: path,
		Size: size,
	}
	var result NativeQuickLookResponse
	err := p.Call(MethodNativeQuickLook, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeQuitApp gracefully quit an app by bundle ID.
func (p *Plugin) NativeQuitApp(bundleID string) (bool, error) {
	req := &NativeQuitAppRequest{
		BundleID: bundleID,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodNativeQuitApp, req, &result)
	return result.Result, err
}

// NativeRaiseWindow raise a window to the front.
func (p *Plugin) NativeRaiseWindow(windowID string) error {
	req := &NativeRaiseWindowRequest{
		WindowID: windowID,
	}
	return p.Call(MethodNativeRaiseWindow, req, nil)
}

// NativeRevealInFinder reveal file in Finder.
func (p *Plugin) NativeRevealInFinder(path string) error {
	req := &NativeRevealInFinderRequest{
		Path: path,
	}
	return p.Call(MethodNativeRevealInFinder, req, nil)
}

// NativeRunApplescript execute an AppleScript via osascript.
func (p *Plugin) NativeRunApplescript(script string) (*NativeRunApplescriptResponse, error) {
	req := &NativeRunApplescriptRequest{
		Script: script,
	}
	var result NativeRunApplescriptResponse
	err := p.Call(MethodNativeRunApplescript, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeRunningApps list all running applications.
func (p *Plugin) NativeRunningApps() ([]RunningApp, error) {
	var result struct {
		Apps []RunningApp `json:"apps"`
	}
	err := p.Call(MethodNativeRunningApps, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Apps, nil
}

// NativeScreenLock lock the screen.
func (p *Plugin) NativeScreenLock() error {
	return p.Call(MethodNativeScreenLock, nil, nil)
}

// NativeScreenshot capture a screenshot as base64-encoded PNG.
func (p *Plugin) NativeScreenshot(displayID json.RawMessage, region json.RawMessage, windowID json.RawMessage) (*NativeScreenshotResponse, error) {
	req := &NativeScreenshotRequest{
		DisplayID: displayID,
		Region: region,
		WindowID: windowID,
	}
	var result NativeScreenshotResponse
	err := p.Call(MethodNativeScreenshot, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeSelectedFinderItems get Finder selection.
func (p *Plugin) NativeSelectedFinderItems() ([]string, error) {
	var result struct {
		Paths []string `json:"paths"`
	}
	err := p.Call(MethodNativeSelectedFinderItems, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Paths, nil
}

// NativeSetAudioDevice set the default audio input or output device.
func (p *Plugin) NativeSetAudioDevice(deviceType string, uid string) error {
	req := &NativeSetAudioDeviceRequest{
		DeviceType: deviceType,
		UID: uid,
	}
	return p.Call(MethodNativeSetAudioDevice, req, nil)
}

// NativeSetBrightness set display brightness (0.0-1.0).
func (p *Plugin) NativeSetBrightness(brightness float64, displayID json.RawMessage) error {
	req := &NativeSetBrightnessRequest{
		Brightness: brightness,
		DisplayID: displayID,
	}
	return p.Call(MethodNativeSetBrightness, req, nil)
}

// NativeSetDarkMode set dark or light mode.
func (p *Plugin) NativeSetDarkMode(dark bool) error {
	req := &NativeSetDarkModeRequest{
		Dark: dark,
	}
	return p.Call(MethodNativeSetDarkMode, req, nil)
}

// NativeSetDnd toggle Do Not Disturb.
func (p *Plugin) NativeSetDnd(enabled bool) error {
	req := &NativeSetDndRequest{
		Enabled: enabled,
	}
	return p.Call(MethodNativeSetDnd, req, nil)
}

// NativeSetVolume set system volume (0.0–1.0).
func (p *Plugin) NativeSetVolume(volume float64) error {
	req := &NativeSetVolumeRequest{
		Volume: volume,
	}
	return p.Call(MethodNativeSetVolume, req, nil)
}

// NativeSetWindowAlpha set window transparency.
func (p *Plugin) NativeSetWindowAlpha(alpha float64, windowID string) error {
	req := &NativeSetWindowAlphaRequest{
		Alpha: alpha,
		WindowID: windowID,
	}
	return p.Call(MethodNativeSetWindowAlpha, req, nil)
}

// NativeSetWindowLevel set a window's level (floating, normal, below).
func (p *Plugin) NativeSetWindowLevel(level string, windowID string) (bool, error) {
	req := &NativeSetWindowLevelRequest{
		Level: level,
		WindowID: windowID,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodNativeSetWindowLevel, req, &result)
	return result.Result, err
}

// NativeSpeak speak text using the system text-to-speech engine.
func (p *Plugin) NativeSpeak(rate json.RawMessage, text string, voice json.RawMessage) error {
	req := &NativeSpeakRequest{
		Rate: rate,
		Text: text,
		Voice: voice,
	}
	return p.Call(MethodNativeSpeak, req, nil)
}

// NativeSpotlight search files via Spotlight.
func (p *Plugin) NativeSpotlight(limit *int, query string, scope json.RawMessage) ([]SpotlightResult, error) {
	req := &NativeSpotlightRequest{
		Limit: limit,
		Query: query,
		Scope: scope,
	}
	var result struct {
		Results []SpotlightResult `json:"results"`
	}
	err := p.Call(MethodNativeSpotlight, req, &result)
	if err != nil {
		return nil, err
	}
	return result.Results, nil
}

// NativeSystemUptime get system uptime.
func (p *Plugin) NativeSystemUptime() (*NativeSystemUptimeResponse, error) {
	var result NativeSystemUptimeResponse
	err := p.Call(MethodNativeSystemUptime, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeToggleFullscreen toggle native fullscreen for a window.
func (p *Plugin) NativeToggleFullscreen(windowID string) error {
	req := &NativeToggleFullscreenRequest{
		WindowID: windowID,
	}
	return p.Call(MethodNativeToggleFullscreen, req, nil)
}

// NativeTrash move file to Trash.
func (p *Plugin) NativeTrash(path string) (bool, error) {
	req := &NativeTrashRequest{
		Path: path,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodNativeTrash, req, &result)
	return result.Result, err
}

// NativeUnhideApp unhide a hidden application.
func (p *Plugin) NativeUnhideApp(bundleID string) error {
	req := &NativeUnhideAppRequest{
		BundleID: bundleID,
	}
	return p.Call(MethodNativeUnhideApp, req, nil)
}

// NativeUnminimizeWindow restore a minimized window by ID.
func (p *Plugin) NativeUnminimizeWindow(windowID string) error {
	req := &NativeUnminimizeWindowRequest{
		WindowID: windowID,
	}
	return p.Call(MethodNativeUnminimizeWindow, req, nil)
}

// NativeUnobserveWindows stop observing window events (STUB).
func (p *Plugin) NativeUnobserveWindows(subscriptionID string) (bool, error) {
	req := &NativeUnobserveWindowsRequest{
		SubscriptionID: subscriptionID,
	}
	var result struct {
		Result bool `json:"result"`
	}
	err := p.Call(MethodNativeUnobserveWindows, req, &result)
	return result.Result, err
}

// NativeVolume get system volume and mute state.
func (p *Plugin) NativeVolume() (*NativeVolumeResponse, error) {
	var result NativeVolumeResponse
	err := p.Call(MethodNativeVolume, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeWarpCursor move the cursor to a position.
func (p *Plugin) NativeWarpCursor(x int, y int) error {
	req := &NativeWarpCursorRequest{
		X: x,
		Y: y,
	}
	return p.Call(MethodNativeWarpCursor, req, nil)
}

// NativeWifi get WiFi interface information.
func (p *Plugin) NativeWifi() (*NativeWifiResponse, error) {
	var result NativeWifiResponse
	err := p.Call(MethodNativeWifi, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// NativeWorldModel get a snapshot of all windows and displays (with managed HUD windows).
func (p *Plugin) NativeWorldModel(onScreen *bool) (*WorldModel, error) {
	req := &NativeWorldModelRequest{
		OnScreen: onScreen,
	}
	var result WorldModel
	err := p.Call(MethodNativeWorldModel, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SelectionPick resolve a selection pick by index — clears selection state, emits event, closes HUD.
func (p *Plugin) SelectionPick(index int) (*SelectionPickResponse, error) {
	req := &SelectionPickRequest{
		Index: index,
	}
	var result SelectionPickResponse
	err := p.Call(MethodSelectionPick, req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SelectionSet show the selection HUD with items for the user to pick from.
func (p *Plugin) SelectionSet(channel json.RawMessage, items json.RawMessage, title json.RawMessage) error {
	req := &SelectionSetRequest{
		Channel: channel,
		Items: items,
		Title: title,
	}
	return p.Call(MethodSelectionSet, req, nil)
}

// SessionEndCleanup tear down input-session HUD/tag state and emit session_ended event.
func (p *Plugin) SessionEndCleanup() (*SessionEndCleanupResponse, error) {
	var result SessionEndCleanupResponse
	err := p.Call(MethodSessionEndCleanup, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SettingsRulesCreate create a new user voice command from settings-UI signals.
func (p *Plugin) SettingsRulesCreate(newruleactionjson json.RawMessage, newruleactiontype json.RawMessage, newruleactionval json.RawMessage, newrulecategory json.RawMessage, newruleclearstags json.RawMessage, newruledescription json.RawMessage, newrulephrase json.RawMessage, newrulerequirestags json.RawMessage, newrulesetstags json.RawMessage) error {
	req := &SettingsRulesCreateRequest{
		Newruleactionjson: newruleactionjson,
		Newruleactiontype: newruleactiontype,
		Newruleactionval: newruleactionval,
		Newrulecategory: newrulecategory,
		Newruleclearstags: newruleclearstags,
		Newruledescription: newruledescription,
		Newrulephrase: newrulephrase,
		Newrulerequirestags: newrulerequirestags,
		Newrulesetstags: newrulesetstags,
	}
	return p.Call(MethodSettingsRulesCreate, req, nil)
}

// SettingsRulesUpdate update an existing user voice command from settings-UI signals.
func (p *Plugin) SettingsRulesUpdate(canonical string, newruleactionjson json.RawMessage, newruleactiontype json.RawMessage, newruleactionval json.RawMessage, newrulecategory json.RawMessage, newruleclearstags json.RawMessage, newruledescription json.RawMessage, newrulephrase json.RawMessage, newrulerequirestags json.RawMessage, newrulesetstags json.RawMessage) error {
	req := &SettingsRulesUpdateRequest{
		Canonical: canonical,
		Newruleactionjson: newruleactionjson,
		Newruleactiontype: newruleactiontype,
		Newruleactionval: newruleactionval,
		Newrulecategory: newrulecategory,
		Newruleclearstags: newruleclearstags,
		Newruledescription: newruledescription,
		Newrulephrase: newrulephrase,
		Newrulerequirestags: newrulerequirestags,
		Newrulesetstags: newrulesetstags,
	}
	return p.Call(MethodSettingsRulesUpdate, req, nil)
}

// SystemLaunchApp launch an app and post a 'Launching' notification to the HUD.
func (p *Plugin) SystemLaunchApp(bundleID string, newInstance *bool) error {
	req := &SystemLaunchAppRequest{
		BundleID: bundleID,
		NewInstance: newInstance,
	}
	return p.Call(MethodSystemLaunchApp, req, nil)
}

// SystemNotify show a HUD notification with title and body text.
func (p *Plugin) SystemNotify(body string, durationSecs json.RawMessage, title string) error {
	req := &SystemNotifyRequest{
		Body: body,
		DurationSecs: durationSecs,
		Title: title,
	}
	return p.Call(MethodSystemNotify, req, nil)
}

// SystemRunShell run a shell command via /bin/bash -c (security-sensitive).
func (p *Plugin) SystemRunShell(command string) error {
	req := &SystemRunShellRequest{
		Command: command,
	}
	return p.Call(MethodSystemRunShell, req, nil)
}

// TagsGet get all active tags.
func (p *Plugin) TagsGet() ([]string, error) {
	var result struct {
		Tags []string `json:"tags"`
	}
	err := p.Call(MethodTagsGet, nil, &result)
	if err != nil {
		return nil, err
	}
	return result.Tags, nil
}

// TagsModify set and/or clear active tags.
func (p *Plugin) TagsModify(clear []string, clearScoped *bool, set []string) ([]string, error) {
	req := &TagsModifyRequest{
		Clear: clear,
		ClearScoped: clearScoped,
		Set: set,
	}
	var result struct {
		Tags []string `json:"tags"`
	}
	err := p.Call(MethodTagsModify, req, &result)
	if err != nil {
		return nil, err
	}
	return result.Tags, nil
}
