// AUTO-GENERATED by emit-sdk — do not edit.
// Run: just contracts

package shared

import "encoding/json"

// Ensure json import is used.
var _ json.RawMessage

// ===== Shared types (from components/schemas) =====

// AXElementInfo is auto-generated from the OpenRPC spec.
type AXElementInfo struct {
	Actions []string `json:"actions"`
	Attributes []string `json:"attributes"`
	ChildrenCount int `json:"children_count"`
	Description json.RawMessage `json:"description,omitempty"`
	Enabled bool `json:"enabled"`
	Focused bool `json:"focused"`
	Path []AXPathSegment `json:"path"`
	Position json.RawMessage `json:"position,omitempty"`
	Role string `json:"role"`
	Size json.RawMessage `json:"size,omitempty"`
	Subrole json.RawMessage `json:"subrole,omitempty"`
	Title json.RawMessage `json:"title,omitempty"`
	Value json.RawMessage `json:"value,omitempty"`
}

// AXElementNode is auto-generated from the OpenRPC spec.
type AXElementNode struct {
	Children []AXElementNode `json:"children"`
	Element AXElementInfo `json:"element"`
}

// AXElementRef is auto-generated from the OpenRPC spec.
type AXElementRef struct {
	Path []AXPathSegment `json:"path"`
	Pid int `json:"pid"`
}

// AXPathSegment is auto-generated from the OpenRPC spec.
type AXPathSegment struct {
	Index int `json:"index"`
	Role string `json:"role"`
}

// ActionFieldSchema is auto-generated from the OpenRPC spec.
type ActionFieldSchema struct {
	EnumValues []string `json:"enum_values"`
	FieldType FieldType `json:"field_type"`
	Fields []ActionFieldSchema `json:"fields"`
	Key string `json:"key"`
	Label string `json:"label"`
	Placeholder json.RawMessage `json:"placeholder,omitempty"`
	Required bool `json:"required"`
}

// ActionTypeSchema is auto-generated from the OpenRPC spec.
type ActionTypeSchema struct {
	Fields []ActionFieldSchema `json:"fields"`
	Label string `json:"label"`
}

// ActiveSpace is auto-generated from the OpenRPC spec.
type ActiveSpace struct {
	DisplayID int `json:"display_id"`
	SpaceID int `json:"space_id"`
}

// AudioDevice is auto-generated from the OpenRPC spec.
type AudioDevice struct {
	ID int `json:"id"`
	IsDefaultInput bool `json:"is_default_input"`
	IsDefaultOutput bool `json:"is_default_output"`
	IsInput bool `json:"is_input"`
	IsOutput bool `json:"is_output"`
	Name string `json:"name"`
	UID string `json:"uid"`
}

// BleCharacteristic is auto-generated from the OpenRPC spec.
type BleCharacteristic struct {
	Properties []string `json:"properties"`
	Uuid string `json:"uuid"`
}

// BleService is auto-generated from the OpenRPC spec.
type BleService struct {
	Characteristics []BleCharacteristic `json:"characteristics"`
	Uuid string `json:"uuid"`
}

// BleWriteEntry is auto-generated from the OpenRPC spec.
type BleWriteEntry struct {
	CharacteristicUuid string `json:"characteristic_uuid"`
	Data []int `json:"data"`
	ServiceUuid string `json:"service_uuid"`
	WriteType string `json:"write_type"`
}

// BluetoothDevice is auto-generated from the OpenRPC spec.
type BluetoothDevice struct {
	Address string `json:"address"`
	DeviceType json.RawMessage `json:"device_type,omitempty"`
	IsConnected bool `json:"is_connected"`
	IsPaired bool `json:"is_paired"`
	Name string `json:"name"`
}

// ClipboardContents is auto-generated from the OpenRPC spec.
type ClipboardContents struct {
	AvailableTypes []string `json:"available_types"`
	ContentType string `json:"content_type"`
	FileUrls json.RawMessage `json:"file_urls,omitempty"`
	ImageBase64 json.RawMessage `json:"image_base64,omitempty"`
	Text json.RawMessage `json:"text,omitempty"`
}

// ClipboardWriteItem is auto-generated from the OpenRPC spec.
type ClipboardWriteItem struct {
	ContentType string `json:"content_type"`
	FileUrls json.RawMessage `json:"file_urls,omitempty"`
	ImageBase64 json.RawMessage `json:"image_base64,omitempty"`
	Text json.RawMessage `json:"text,omitempty"`
}

// CollectionsListItem is auto-generated from the OpenRPC spec.
type CollectionsListItem struct {
	ID string `json:"id"`
	Source string `json:"source"`
	Subtitle json.RawMessage `json:"subtitle,omitempty"`
	Title string `json:"title"`
}

// CollectionsListSection is auto-generated from the OpenRPC spec.
type CollectionsListSection struct {
	EntryCount int `json:"entry_count"`
	Items []CollectionsListItem `json:"items"`
	Label string `json:"label"`
	Name string `json:"name"`
	Plugin string `json:"plugin"`
}

// CommandRowData is auto-generated from the OpenRPC spec.
type CommandRowData struct {
	Action string `json:"action"`
	ActionJson json.RawMessage `json:"action_json,omitempty"`
	Canonical string `json:"canonical"`
	Category string `json:"category"`
	IsUser bool `json:"is_user"`
	Pattern string `json:"pattern"`
	PluginName string `json:"plugin_name"`
	Tier string `json:"tier"`
}

// DeliveredNotification is auto-generated from the OpenRPC spec.
type DeliveredNotification struct {
	Body json.RawMessage `json:"body,omitempty"`
	DeliveredAt string `json:"delivered_at"`
	ID string `json:"id"`
	Title string `json:"title"`
}

// DiscoverItem is auto-generated from the OpenRPC spec.
type DiscoverItem struct {
	ID string `json:"id"`
	Subtitle json.RawMessage `json:"subtitle,omitempty"`
	Tag string `json:"tag"`
	Title string `json:"title"`
}

// DisplayInfo is auto-generated from the OpenRPC spec.
type DisplayInfo struct {
	H int `json:"h"`
	ID int `json:"id"`
	VisibleH int `json:"visible_h"`
	VisibleW int `json:"visible_w"`
	VisibleX int `json:"visible_x"`
	VisibleY int `json:"visible_y"`
	W int `json:"w"`
	X int `json:"x"`
	Y int `json:"y"`
}

// DisplayMetadata is auto-generated from the OpenRPC spec.
type DisplayMetadata struct {
	DisplayID int `json:"display_id"`
	H int `json:"h"`
	IsBuiltin bool `json:"is_builtin"`
	IsPrimary bool `json:"is_primary"`
	Name string `json:"name"`
	RefreshRate float64 `json:"refresh_rate"`
	ResolutionH int `json:"resolution_h"`
	ResolutionW int `json:"resolution_w"`
	ScaleFactor float64 `json:"scale_factor"`
	VisibleH int `json:"visible_h"`
	VisibleW int `json:"visible_w"`
	VisibleX int `json:"visible_x"`
	VisibleY int `json:"visible_y"`
	W int `json:"w"`
	X int `json:"x"`
	Y int `json:"y"`
}

// FieldType is auto-generated from the OpenRPC spec.
// The declared shape of a single action-type field. See `ActionFieldSchema`.
// 
// Wire format uses snake_case strings (`"string"`, `"int"`, `"enum"`, …).
// Unknown values fail deserialization — that's deliberate: a typo in
// `plugin.json` should surface at load time, not at dispatch. The `Json`
// variant is the documented escape hatch for shapes too dynamic to
// declare statically.
type FieldType string

const (
	FieldTypeString FieldType = "string"
	FieldTypeInt FieldType = "int"
	FieldTypeNumber FieldType = "number"
	FieldTypeBoolean FieldType = "boolean"
	FieldTypeStringArray FieldType = "string[]"
	FieldTypeEnum FieldType = "enum"
	FieldTypeObject FieldType = "object"
	FieldTypeJson FieldType = "json"
)

// Frame is auto-generated from the OpenRPC spec.
type Frame struct {
	H int `json:"h"`
	W int `json:"w"`
	X int `json:"x"`
	Y int `json:"y"`
}

// HidDeviceEntry is auto-generated from the OpenRPC spec.
type HidDeviceEntry struct {
	Axes int `json:"axes"`
	BleUuid json.RawMessage `json:"ble_uuid,omitempty"`
	Buttons int `json:"buttons"`
	ID string `json:"id"`
	Product string `json:"product"`
	ProductID int `json:"product_id"`
	Seized bool `json:"seized"`
	Transport string `json:"transport"`
	VendorID int `json:"vendor_id"`
}

// HidElementEntry is auto-generated from the OpenRPC spec.
type HidElementEntry struct {
	BitOffset int `json:"bit_offset"`
	ByteOffset int `json:"byte_offset"`
	LogicalMax int `json:"logical_max"`
	LogicalMin int `json:"logical_min"`
	ReportCount int `json:"report_count"`
	ReportID int `json:"report_id"`
	ReportSize int `json:"report_size"`
	Type string `json:"type"`
	Usage int `json:"usage"`
	UsagePage int `json:"usage_page"`
}

// HudItem is auto-generated from the OpenRPC spec.
type HudItem struct {
	Icon *string `json:"icon,omitempty"`
	ID string `json:"id"`
	Subtitle *string `json:"subtitle,omitempty"`
	Tag *string `json:"tag,omitempty"`
	Title string `json:"title"`
}

// HudResponse is auto-generated from the OpenRPC spec.
type HudResponse struct {
	ContentHTML *string `json:"content_html,omitempty"`
	Footer string `json:"footer"`
	Sections []HudSection `json:"sections,omitempty"`
	Title string `json:"title"`
}

// HudSection is auto-generated from the OpenRPC spec.
type HudSection struct {
	Items []HudItem `json:"items"`
	Title string `json:"title"`
}

// IngestSegmentSpec is auto-generated from the OpenRPC spec.
type IngestSegmentSpec struct {
	Alternatives []string `json:"alternatives"`
	Duration float64 `json:"duration"`
	ID int `json:"id"`
	Start float64 `json:"start"`
	Text string `json:"text"`
}

// InputSource is auto-generated from the OpenRPC spec.
type InputSource struct {
	ID string `json:"id"`
	IsActive bool `json:"is_active"`
	Name string `json:"name"`
}

// InstalledApp is auto-generated from the OpenRPC spec.
type InstalledApp struct {
	BundleID string `json:"bundle_id"`
	Name string `json:"name"`
}

// ListCommandItem is auto-generated from the OpenRPC spec.
type ListCommandItem struct {
	ID string `json:"id"`
	Subtitle json.RawMessage `json:"subtitle,omitempty"`
	Tag json.RawMessage `json:"tag,omitempty"`
	Title string `json:"title"`
}

// ListCommandSection is auto-generated from the OpenRPC spec.
type ListCommandSection struct {
	Items []ListCommandItem `json:"items"`
	Title string `json:"title"`
}

// LoginItem is auto-generated from the OpenRPC spec.
type LoginItem struct {
	BundleID json.RawMessage `json:"bundle_id,omitempty"`
	Hidden bool `json:"hidden"`
	Name string `json:"name"`
	Path string `json:"path"`
}

// MenuItem is auto-generated from the OpenRPC spec.
type MenuItem struct {
	Children []MenuItem `json:"children"`
	Enabled bool `json:"enabled"`
	Index int `json:"index"`
	Shortcut json.RawMessage `json:"shortcut,omitempty"`
	Title string `json:"title"`
}

// MergeStrategy is auto-generated from the OpenRPC spec.
// How contributions to a shared store are merged when read.
type MergeStrategy string

const (
	MergeStrategyAuthoritative MergeStrategy = "authoritative"
	MergeStrategyCollect MergeStrategy = "collect"
	MergeStrategyKeyed MergeStrategy = "keyed"
)

// OnActionStatus is auto-generated from the OpenRPC spec.
type OnActionStatus string

const (
	OnActionStatusOk OnActionStatus = "ok"
	OnActionStatusError OnActionStatus = "error"
	OnActionStatusNotHandled OnActionStatus = "not_handled"
)

// RunningApp is auto-generated from the OpenRPC spec.
type RunningApp struct {
	BundleID json.RawMessage `json:"bundle_id,omitempty"`
	IsActive bool `json:"is_active"`
	IsHidden bool `json:"is_hidden"`
	Name string `json:"name"`
	Pid int `json:"pid"`
}

// ScreenshotRegion is auto-generated from the OpenRPC spec.
type ScreenshotRegion struct {
	H int `json:"h"`
	W int `json:"w"`
	X int `json:"x"`
	Y int `json:"y"`
}

// SelectionItemSpec is auto-generated from the OpenRPC spec.
type SelectionItemSpec struct {
	ID string `json:"id"`
	Tag *string `json:"tag,omitempty"`
}

// SettingsListSchemaInfo is auto-generated from the OpenRPC spec.
type SettingsListSchemaInfo struct {
	Description string `json:"description"`
	EntryCount int `json:"entry_count"`
	Label string `json:"label"`
	SourcePlugin string `json:"source_plugin"`
}

// SettingsTagSchemaInfo is auto-generated from the OpenRPC spec.
type SettingsTagSchemaInfo struct {
	Description string `json:"description"`
	Label string `json:"label"`
	SourcePlugin string `json:"source_plugin"`
}

// SpaceInfo is auto-generated from the OpenRPC spec.
type SpaceInfo struct {
	DisplayID int `json:"display_id"`
	IsActive bool `json:"is_active"`
	SpaceID int `json:"space_id"`
	SpaceType string `json:"space_type"`
}

// SpotlightResult is auto-generated from the OpenRPC spec.
type SpotlightResult struct {
	Kind string `json:"kind"`
	Modified string `json:"modified"`
	Name string `json:"name"`
	Path string `json:"path"`
	Size json.RawMessage `json:"size,omitempty"`
}

// TileableEntry is auto-generated from the OpenRPC spec.
type TileableEntry struct {
	Tileable bool `json:"tileable"`
	WindowID string `json:"window_id"`
}

// WindowBounds is auto-generated from the OpenRPC spec.
type WindowBounds struct {
	H int `json:"h"`
	W int `json:"w"`
	X int `json:"x"`
	Y int `json:"y"`
}

// WindowFrame is auto-generated from the OpenRPC spec.
type WindowFrame struct {
	H int `json:"h"`
	W int `json:"w"`
	WindowID string `json:"window_id"`
	X int `json:"x"`
	Y int `json:"y"`
}

// WindowInfo is auto-generated from the OpenRPC spec.
type WindowInfo struct {
	AppID string `json:"app_id"`
	AppName string `json:"app_name"`
	H int `json:"h"`
	ID string `json:"id"`
	Source string `json:"source"`
	Title string `json:"title"`
	W int `json:"w"`
	X int `json:"x"`
	Y int `json:"y"`
}

// WorldModel is auto-generated from the OpenRPC spec.
type WorldModel struct {
	ActiveApp *string `json:"active_app,omitempty"`
	ActiveWindowID *string `json:"active_window_id,omitempty"`
	Displays []DisplayInfo `json:"displays"`
	KeyboardLayoutID string `json:"keyboard_layout_id"`
	Windows []WindowInfo `json:"windows"`
}

// ===== Plugin → Actuator request/response types =====

// ActionsListResponse is the response type for actions.list.
type ActionsListResponse struct {
	Actions map[string]ActionTypeSchema `json:"actions"`
}

// CollectionDeleteRequest is the request type for collection.delete.
type CollectionDeleteRequest struct {
	Name string `json:"name"`
}

// CollectionDeleteResponse is the response type for collection.delete.
type CollectionDeleteResponse struct {
	Ok bool `json:"ok"`
}

// CollectionGetRequest is the request type for collection.get.
type CollectionGetRequest struct {
	Name string `json:"name"`
}

// CollectionGetResponse is the response type for collection.get.
type CollectionGetResponse struct {
	Data json.RawMessage `json:"data"`
	Entries json.RawMessage `json:"entries,omitempty"`
	Introducer string `json:"introducer"`
	Merge MergeStrategy `json:"merge"`
	Name string `json:"name"`
}

// CollectionOverrideRequest is the request type for collection.override.
type CollectionOverrideRequest struct {
	Action string `json:"action"`
	Collection string `json:"collection"`
	Fields json.RawMessage `json:"fields,omitempty"`
	ID json.RawMessage `json:"id,omitempty"`
}

// CollectionOverrideResponse is the response type for collection.override.
type CollectionOverrideResponse struct {
	Ok bool `json:"ok"`
}

// CollectionPushRequest is the request type for collection.push.
type CollectionPushRequest struct {
	Data json.RawMessage `json:"data"`
	Label json.RawMessage `json:"label,omitempty"`
	Name string `json:"name"`
}

// CollectionPushResponse is the response type for collection.push.
type CollectionPushResponse struct {
	Ok bool `json:"ok"`
}

// CollectionsListRequest is the request type for collections.list.
type CollectionsListRequest struct {
	Kind json.RawMessage `json:"kind,omitempty"`
}

// CollectionsListResponse is the response type for collections.list.
type CollectionsListResponse struct {
	Sections []CollectionsListSection `json:"sections"`
}

// CommandsDiscoverRequest is the request type for commands.discover.
type CommandsDiscoverRequest struct {
	ActiveTags json.RawMessage `json:"active_tags,omitempty"`
	RequireTag json.RawMessage `json:"require_tag,omitempty"`
	Words json.RawMessage `json:"words,omitempty"`
}

// CommandsDiscoverResponse is the response type for commands.discover.
type CommandsDiscoverResponse struct {
	Items []DiscoverItem `json:"items"`
	Title string `json:"title"`
}

// CommandsHasPartialRequest is the request type for commands.has_partial.
type CommandsHasPartialRequest struct {
	ActiveTags json.RawMessage `json:"active_tags,omitempty"`
	Words []string `json:"words,omitempty"`
}

// CommandsHasPartialResponse is the response type for commands.has_partial.
type CommandsHasPartialResponse struct {
	HasPartial bool `json:"has_partial"`
	NextList json.RawMessage `json:"next_list,omitempty"`
}

// CommandsListResponse is the response type for commands.list.
type CommandsListResponse struct {
	Footer string `json:"footer"`
	Sections []ListCommandSection `json:"sections"`
	Title string `json:"title"`
}

// CommandsMatchRequest is the request type for commands.match.
type CommandsMatchRequest struct {
	ActiveTags json.RawMessage `json:"active_tags,omitempty"`
	Words []string `json:"words,omitempty"`
}

// CommandsMatchResponse is the response type for commands.match.
type CommandsMatchResponse struct {
	Action json.RawMessage `json:"action,omitempty"`
	Args []json.RawMessage `json:"args"`
	ClearsTags []string `json:"clears_tags"`
	ConsumedCount int `json:"consumed_count"`
	Matched bool `json:"matched"`
	OwnerPlugin json.RawMessage `json:"owner_plugin,omitempty"`
	RequiresTags []string `json:"requires_tags"`
	SetsTags []string `json:"sets_tags"`
}

// CommandsPushRequest is the request type for commands.push.
type CommandsPushRequest struct {
	Commands json.RawMessage `json:"commands,omitempty"`
}

// CommandsPushResponse is the response type for commands.push.
type CommandsPushResponse struct {
	Count int `json:"count"`
	Ok bool `json:"ok"`
}

// ControlSignalRequest is the request type for control.signal.
type ControlSignalRequest struct {
	Signal string `json:"signal"`
}

// ControlSignalResponse is the response type for control.signal.
type ControlSignalResponse struct {
	Ok bool `json:"ok"`
}

// DispatchRequest is the request type for dispatch.
type DispatchRequest struct {
	Action json.RawMessage `json:"action"`
}

// DispatchResponse is the response type for dispatch.
type DispatchResponse struct {
	ControlMessage json.RawMessage `json:"control_message,omitempty"`
	Handler json.RawMessage `json:"handler,omitempty"`
	Message json.RawMessage `json:"message,omitempty"`
	Result json.RawMessage `json:"result,omitempty"`
	Status string `json:"status"`
}

// EventsAppendRequest is the request type for events.append.
type EventsAppendRequest struct {
	Data json.RawMessage `json:"data,omitempty"`
	EventType string `json:"event_type"`
	SessionID *string `json:"session_id,omitempty"`
}

// EventsAppendResponse is the response type for events.append.
type EventsAppendResponse struct {
	Ok bool `json:"ok"`
}

// EventsEmitRequest is the request type for events.emit.
type EventsEmitRequest struct {
	CorrelationID json.RawMessage `json:"correlation_id,omitempty"`
	Data json.RawMessage `json:"data,omitempty"`
	EventType string `json:"event_type"`
}

// EventsEmitResponse is the response type for events.emit.
type EventsEmitResponse struct {
	Ok bool `json:"ok"`
}

// HUDCreateChannelRequest is the request type for hud.create_channel.
type HUDCreateChannelRequest struct {
	AcceptsInput *bool `json:"accepts_input,omitempty"`
	Anchor json.RawMessage `json:"anchor,omitempty"`
	Channel string `json:"channel"`
	Description *string `json:"description,omitempty"`
	FollowsFocus *bool `json:"follows_focus,omitempty"`
	MinHeight *int `json:"min_height,omitempty"`
	Width *int `json:"width,omitempty"`
}

// HUDCreateChannelResponse is the response type for hud.create_channel.
type HUDCreateChannelResponse struct {
	Ok bool `json:"ok"`
}

// HUDHideRequest is the request type for hud.hide.
type HUDHideRequest struct {
	Channel string `json:"channel"`
}

// HUDHideResponse is the response type for hud.hide.
type HUDHideResponse struct {
	Ok bool `json:"ok"`
}

// HUDPushRequest is the request type for hud.push.
type HUDPushRequest struct {
	Channel string `json:"channel"`
	Fragments json.RawMessage `json:"fragments"`
}

// HUDPushResponse is the response type for hud.push.
type HUDPushResponse struct {
	Ok bool `json:"ok"`
}

// HUDRemoveChannelRequest is the request type for hud.remove_channel.
type HUDRemoveChannelRequest struct {
	Channel string `json:"channel"`
}

// HUDRemoveChannelResponse is the response type for hud.remove_channel.
type HUDRemoveChannelResponse struct {
	Ok bool `json:"ok"`
	Removed bool `json:"removed"`
}

// HUDSetSizeRequest is the request type for hud.set_size.
type HUDSetSizeRequest struct {
	Channel string `json:"channel"`
	Height int `json:"height"`
}

// HUDSetSizeResponse is the response type for hud.set_size.
type HUDSetSizeResponse struct {
	Ok bool `json:"ok"`
}

// HUDShowRequest is the request type for hud.show.
type HUDShowRequest struct {
	Channel string `json:"channel"`
}

// HUDShowResponse is the response type for hud.show.
type HUDShowResponse struct {
	Ok bool `json:"ok"`
}

// InputClickRequest is the request type for input.click.
type InputClickRequest struct {
	Button *string `json:"button,omitempty"`
}

// InputClickResponse is the response type for input.click.
type InputClickResponse struct {
	Ok bool `json:"ok"`
}

// InputClipboardActionRequest is the request type for input.clipboard_action.
type InputClipboardActionRequest struct {
	Action string `json:"action"`
	Text json.RawMessage `json:"text,omitempty"`
}

// InputClipboardActionResponse is the response type for input.clipboard_action.
type InputClipboardActionResponse struct {
	Ok bool `json:"ok"`
}

// InputClipboardReadRequest is the request type for input.clipboard_read.
type InputClipboardReadRequest struct {
	ContentType string `json:"content_type"`
}

// InputClipboardReadResponse is the response type for input.clipboard_read.
type InputClipboardReadResponse struct {
	AvailableTypes []string `json:"available_types"`
	ContentType string `json:"content_type"`
	FileUrls json.RawMessage `json:"file_urls,omitempty"`
	ImageBase64 json.RawMessage `json:"image_base64,omitempty"`
	Text json.RawMessage `json:"text,omitempty"`
}

// InputClipboardReadAllResponse is the response type for input.clipboard_read_all.
type InputClipboardReadAllResponse struct {
	Items []ClipboardContents `json:"items"`
}

// InputClipboardWriteRequest is the request type for input.clipboard_write.
type InputClipboardWriteRequest struct {
	ContentType string `json:"content_type"`
	Data string `json:"data"`
}

// InputClipboardWriteResponse is the response type for input.clipboard_write.
type InputClipboardWriteResponse struct {
	Ok bool `json:"ok"`
}

// InputClipboardWriteItemsRequest is the request type for input.clipboard_write_items.
type InputClipboardWriteItemsRequest struct {
	Items []ClipboardWriteItem `json:"items,omitempty"`
}

// InputClipboardWriteItemsResponse is the response type for input.clipboard_write_items.
type InputClipboardWriteItemsResponse struct {
	Ok bool `json:"ok"`
}

// InputDoubleClickRequest is the request type for input.double_click.
type InputDoubleClickRequest struct {
	X json.RawMessage `json:"x,omitempty"`
	Y json.RawMessage `json:"y,omitempty"`
}

// InputDoubleClickResponse is the response type for input.double_click.
type InputDoubleClickResponse struct {
	Ok bool `json:"ok"`
}

// InputDragRequest is the request type for input.drag.
type InputDragRequest struct {
	DurationMs *int `json:"duration_ms,omitempty"`
	FromX int `json:"from_x"`
	FromY int `json:"from_y"`
	ToX int `json:"to_x"`
	ToY int `json:"to_y"`
}

// InputDragResponse is the response type for input.drag.
type InputDragResponse struct {
	Ok bool `json:"ok"`
}

// InputListInputSourcesResponse is the response type for input.list_input_sources.
type InputListInputSourcesResponse struct {
	Sources []InputSource `json:"sources"`
}

// InputMouseButtonRequest is the request type for input.mouse_button.
type InputMouseButtonRequest struct {
	Button *string `json:"button,omitempty"`
	Direction string `json:"direction"`
}

// InputMouseButtonResponse is the response type for input.mouse_button.
type InputMouseButtonResponse struct {
	Ok bool `json:"ok"`
}

// InputPressKeyRequest is the request type for input.press_key.
type InputPressKeyRequest struct {
	Code json.RawMessage `json:"code,omitempty"`
	Modifiers []string `json:"modifiers,omitempty"`
	Name json.RawMessage `json:"name,omitempty"`
}

// InputPressKeyResponse is the response type for input.press_key.
type InputPressKeyResponse struct {
	Ok bool `json:"ok"`
}

// InputRawKeyRequest is the request type for input.raw_key.
type InputRawKeyRequest struct {
	Code int `json:"code"`
	Direction string `json:"direction"`
}

// InputRawKeyResponse is the response type for input.raw_key.
type InputRawKeyResponse struct {
	Ok bool `json:"ok"`
}

// InputRightClickRequest is the request type for input.right_click.
type InputRightClickRequest struct {
	X json.RawMessage `json:"x,omitempty"`
	Y json.RawMessage `json:"y,omitempty"`
}

// InputRightClickResponse is the response type for input.right_click.
type InputRightClickResponse struct {
	Ok bool `json:"ok"`
}

// InputScrollRequest is the request type for input.scroll.
type InputScrollRequest struct {
	Amount *int `json:"amount,omitempty"`
	Direction string `json:"direction"`
}

// InputScrollResponse is the response type for input.scroll.
type InputScrollResponse struct {
	Ok bool `json:"ok"`
}

// InputSwitchInputSourceRequest is the request type for input.switch_input_source.
type InputSwitchInputSourceRequest struct {
	SourceID string `json:"source_id"`
}

// InputSwitchInputSourceResponse is the response type for input.switch_input_source.
type InputSwitchInputSourceResponse struct {
	Result bool `json:"result"`
}

// InputTypeTextRequest is the request type for input.type_text.
type InputTypeTextRequest struct {
	Text string `json:"text"`
}

// InputTypeTextResponse is the response type for input.type_text.
type InputTypeTextResponse struct {
	Ok bool `json:"ok"`
}

// KeyNamesSetRequest is the request type for key_names.set.
type KeyNamesSetRequest struct {
	Names map[string]int `json:"names,omitempty"`
}

// KeyNamesSetResponse is the response type for key_names.set.
type KeyNamesSetResponse struct {
	Count int `json:"count"`
	Ok bool `json:"ok"`
}

// KeybindsRegisterRequest is the request type for keybinds.register.
type KeybindsRegisterRequest struct {
	Snapshot json.RawMessage `json:"snapshot"`
}

// KeybindsRegisterResponse is the response type for keybinds.register.
type KeybindsRegisterResponse struct {
	Count int `json:"count"`
	Ok bool `json:"ok"`
}

// MatchAliasesGetResponse is the response type for match_aliases.get.
type MatchAliasesGetResponse struct {
	Aliases map[string]string `json:"aliases"`
}

// MatchAliasesSetRequest is the request type for match_aliases.set.
type MatchAliasesSetRequest struct {
	Aliases map[string]string `json:"aliases,omitempty"`
}

// MatchAliasesSetResponse is the response type for match_aliases.set.
type MatchAliasesSetResponse struct {
	Count int `json:"count"`
	Ok bool `json:"ok"`
}

// NativeActivateAppRequest is the request type for native.activate_app.
type NativeActivateAppRequest struct {
	AllWindows *bool `json:"all_windows,omitempty"`
	BundleID string `json:"bundle_id"`
}

// NativeActivateAppResponse is the response type for native.activate_app.
type NativeActivateAppResponse struct {
	Ok bool `json:"ok"`
}

// NativeActiveSpaceResponse is the response type for native.active_space.
type NativeActiveSpaceResponse struct {
	Active []ActiveSpace `json:"active"`
}

// NativeAppIconRequest is the request type for native.app_icon.
type NativeAppIconRequest struct {
	BundleID string `json:"bundle_id"`
	Size *int `json:"size,omitempty"`
}

// NativeAppIconResponse is the response type for native.app_icon.
type NativeAppIconResponse struct {
	Format string `json:"format"`
	ImageBase64 string `json:"image_base64"`
}

// NativeAudioDevicesResponse is the response type for native.audio_devices.
type NativeAudioDevicesResponse struct {
	Devices []AudioDevice `json:"devices"`
}

// NativeAxElementAtPointRequest is the request type for native.ax_element_at_point.
type NativeAxElementAtPointRequest struct {
	Pid int `json:"pid"`
	X int `json:"x"`
	Y int `json:"y"`
}

// NativeAxElementAtPointResponse is the response type for native.ax_element_at_point.
type NativeAxElementAtPointResponse struct {
	Actions []string `json:"actions"`
	Attributes []string `json:"attributes"`
	ChildrenCount int `json:"children_count"`
	Description json.RawMessage `json:"description,omitempty"`
	Enabled bool `json:"enabled"`
	Focused bool `json:"focused"`
	Path []AXPathSegment `json:"path"`
	Position json.RawMessage `json:"position,omitempty"`
	Role string `json:"role"`
	Size json.RawMessage `json:"size,omitempty"`
	Subrole json.RawMessage `json:"subrole,omitempty"`
	Title json.RawMessage `json:"title,omitempty"`
	Value json.RawMessage `json:"value,omitempty"`
}

// NativeAxElementTreeRequest is the request type for native.ax_element_tree.
type NativeAxElementTreeRequest struct {
	Depth *int `json:"depth,omitempty"`
	Element AXElementRef `json:"element"`
}

// NativeAxObserveRequest is the request type for native.ax_observe.
type NativeAxObserveRequest struct {
	Notifications []string `json:"notifications,omitempty"`
	Pid int `json:"pid"`
}

// NativeAxObserveResponse is the response type for native.ax_observe.
type NativeAxObserveResponse struct {
	SubscriptionID string `json:"subscription_id"`
}

// NativeAxPerformActionRequest is the request type for native.ax_perform_action.
type NativeAxPerformActionRequest struct {
	Action string `json:"action"`
	Element AXElementRef `json:"element"`
}

// NativeAxPerformActionResponse is the response type for native.ax_perform_action.
type NativeAxPerformActionResponse struct {
	Result bool `json:"result"`
}

// NativeAxReadAttributesRequest is the request type for native.ax_read_attributes.
type NativeAxReadAttributesRequest struct {
	Attributes []string `json:"attributes,omitempty"`
	Element AXElementRef `json:"element"`
}

// NativeAxSetAttributeRequest is the request type for native.ax_set_attribute.
type NativeAxSetAttributeRequest struct {
	Attribute string `json:"attribute"`
	Element AXElementRef `json:"element"`
	Value json.RawMessage `json:"value"`
}

// NativeAxSetAttributeResponse is the response type for native.ax_set_attribute.
type NativeAxSetAttributeResponse struct {
	Result bool `json:"result"`
}

// NativeAxUnobserveRequest is the request type for native.ax_unobserve.
type NativeAxUnobserveRequest struct {
	SubscriptionID string `json:"subscription_id"`
}

// NativeAxUnobserveResponse is the response type for native.ax_unobserve.
type NativeAxUnobserveResponse struct {
	Result bool `json:"result"`
}

// NativeBatchIsTileableRequest is the request type for native.batch_is_tileable.
type NativeBatchIsTileableRequest struct {
	WindowIds []string `json:"window_ids,omitempty"`
}

// NativeBatchIsTileableResponse is the response type for native.batch_is_tileable.
type NativeBatchIsTileableResponse struct {
	Results []TileableEntry `json:"results"`
}

// NativeBatchSetFramesRequest is the request type for native.batch_set_frames.
type NativeBatchSetFramesRequest struct {
	Frames []WindowFrame `json:"frames,omitempty"`
	Readback *bool `json:"readback,omitempty"`
}

// NativeBatchSetFramesResponse is the response type for native.batch_set_frames.
type NativeBatchSetFramesResponse struct {
	Results []WindowFrame `json:"results"`
}

// NativeBatteryResponse is the response type for native.battery.
type NativeBatteryResponse struct {
	IsCharging bool `json:"is_charging"`
	IsPluggedIn bool `json:"is_plugged_in"`
	IsPresent bool `json:"is_present"`
	Level float64 `json:"level"`
	TimeRemainingMinutes json.RawMessage `json:"time_remaining_minutes,omitempty"`
}

// NativeBleDiscoverServicesRequest is the request type for native.ble_discover_services.
type NativeBleDiscoverServicesRequest struct {
	DeviceIdentifier string `json:"device_identifier"`
}

// NativeBleDiscoverServicesResponse is the response type for native.ble_discover_services.
type NativeBleDiscoverServicesResponse struct {
	Services []BleService `json:"services"`
}

// NativeBleSubscribeRequest is the request type for native.ble_subscribe.
type NativeBleSubscribeRequest struct {
	CharacteristicUuid string `json:"characteristic_uuid"`
	DeviceIdentifier string `json:"device_identifier"`
	ServiceUuid string `json:"service_uuid"`
}

// NativeBleSubscribeResponse is the response type for native.ble_subscribe.
type NativeBleSubscribeResponse struct {
	Success bool `json:"success"`
}

// NativeBleSubscribeAllThenWriteRequest is the request type for native.ble_subscribe_all_then_write.
type NativeBleSubscribeAllThenWriteRequest struct {
	DeviceIdentifier string `json:"device_identifier"`
	SubscribeServices []string `json:"subscribe_services,omitempty"`
	Writes []BleWriteEntry `json:"writes,omitempty"`
}

// NativeBleSubscribeAllThenWriteResponse is the response type for native.ble_subscribe_all_then_write.
type NativeBleSubscribeAllThenWriteResponse struct {
	Success bool `json:"success"`
}

// NativeBleWriteRequest is the request type for native.ble_write.
type NativeBleWriteRequest struct {
	CharacteristicUuid string `json:"characteristic_uuid"`
	Data []int `json:"data,omitempty"`
	DeviceIdentifier string `json:"device_identifier"`
	ServiceUuid string `json:"service_uuid"`
	WriteType *string `json:"write_type,omitempty"`
}

// NativeBleWriteResponse is the response type for native.ble_write.
type NativeBleWriteResponse struct {
	Success bool `json:"success"`
}

// NativeBluetoothDevicesResponse is the response type for native.bluetooth_devices.
type NativeBluetoothDevicesResponse struct {
	Devices []BluetoothDevice `json:"devices"`
}

// NativeBordersResponse is the response type for native.borders.
type NativeBordersResponse struct {
	Ok bool `json:"ok"`
}

// NativeBrightnessRequest is the request type for native.brightness.
type NativeBrightnessRequest struct {
	DisplayID json.RawMessage `json:"display_id,omitempty"`
}

// NativeBrightnessResponse is the response type for native.brightness.
type NativeBrightnessResponse struct {
	Brightness float64 `json:"brightness"`
}

// NativeCaptureWindowRequest is the request type for native.capture_window.
type NativeCaptureWindowRequest struct {
	WindowID string `json:"window_id"`
}

// NativeCaptureWindowResponse is the response type for native.capture_window.
type NativeCaptureWindowResponse struct {
	Format string `json:"format"`
	ImageBase64 string `json:"image_base64"`
}

// NativeClickMenuItemRequest is the request type for native.click_menu_item.
type NativeClickMenuItemRequest struct {
	Path []string `json:"path,omitempty"`
	Pid int `json:"pid"`
}

// NativeClickMenuItemResponse is the response type for native.click_menu_item.
type NativeClickMenuItemResponse struct {
	Result bool `json:"result"`
}

// NativeClipboardChangeCountResponse is the response type for native.clipboard_change_count.
type NativeClipboardChangeCountResponse struct {
	Count int `json:"count"`
}

// NativeCloseWindowRequest is the request type for native.close_window.
type NativeCloseWindowRequest struct {
	WindowID string `json:"window_id"`
}

// NativeCloseWindowResponse is the response type for native.close_window.
type NativeCloseWindowResponse struct {
	Ok bool `json:"ok"`
}

// NativeColorAtPointRequest is the request type for native.color_at_point.
type NativeColorAtPointRequest struct {
	X int `json:"x"`
	Y int `json:"y"`
}

// NativeColorAtPointResponse is the response type for native.color_at_point.
type NativeColorAtPointResponse struct {
	A int `json:"a"`
	B int `json:"b"`
	G int `json:"g"`
	Hex string `json:"hex"`
	R int `json:"r"`
}

// NativeCurrentUserResponse is the response type for native.current_user.
type NativeCurrentUserResponse struct {
	FullName string `json:"full_name"`
	HomeDirectory string `json:"home_directory"`
	Username string `json:"username"`
}

// NativeCursorResponse is the response type for native.cursor.
type NativeCursorResponse struct {
	X int `json:"x"`
	Y int `json:"y"`
}

// NativeCursorInfoResponse is the response type for native.cursor_info.
type NativeCursorInfoResponse struct {
	CursorType string `json:"cursor_type"`
	X int `json:"x"`
	Y int `json:"y"`
}

// NativeDarkModeResponse is the response type for native.dark_mode.
type NativeDarkModeResponse struct {
	IsDark bool `json:"is_dark"`
}

// NativeDefaultBrowserResponse is the response type for native.default_browser.
type NativeDefaultBrowserResponse struct {
	BundleID string `json:"bundle_id"`
}

// NativeDismissNotificationRequest is the request type for native.dismiss_notification.
type NativeDismissNotificationRequest struct {
	ID string `json:"id"`
}

// NativeDismissNotificationResponse is the response type for native.dismiss_notification.
type NativeDismissNotificationResponse struct {
	Ok bool `json:"ok"`
}

// NativeDisplaysResponse is the response type for native.displays.
type NativeDisplaysResponse struct {
	Displays []DisplayMetadata `json:"displays"`
}

// NativeDndResponse is the response type for native.dnd.
type NativeDndResponse struct {
	Enabled bool `json:"enabled"`
	FocusName json.RawMessage `json:"focus_name,omitempty"`
}

// NativeFileTagsRequest is the request type for native.file_tags.
type NativeFileTagsRequest struct {
	Path string `json:"path"`
	Tags json.RawMessage `json:"tags,omitempty"`
}

// NativeForceQuitAppRequest is the request type for native.force_quit_app.
type NativeForceQuitAppRequest struct {
	BundleID string `json:"bundle_id"`
}

// NativeForceQuitAppResponse is the response type for native.force_quit_app.
type NativeForceQuitAppResponse struct {
	Result bool `json:"result"`
}

// NativeFrontmostAppResponse is the response type for native.frontmost_app.
type NativeFrontmostAppResponse struct {
	App json.RawMessage `json:"app,omitempty"`
}

// NativeGetWindowInfoRequest is the request type for native.get_window_info.
type NativeGetWindowInfoRequest struct {
	WindowID string `json:"window_id"`
}

// NativeGetWindowInfoResponse is the response type for native.get_window_info.
type NativeGetWindowInfoResponse struct {
	Alpha json.RawMessage `json:"alpha,omitempty"`
	Bounds WindowBounds `json:"bounds"`
	DisplayID int `json:"display_id"`
	IsFocused bool `json:"is_focused"`
	IsFullscreen bool `json:"is_fullscreen"`
	IsMinimized bool `json:"is_minimized"`
	Subrole json.RawMessage `json:"subrole,omitempty"`
	Title json.RawMessage `json:"title,omitempty"`
	WindowID string `json:"window_id"`
}

// NativeHidClaimRequest is the request type for native.hid_claim.
type NativeHidClaimRequest struct {
	DeviceID string `json:"device_id"`
}

// NativeHidClaimResponse is the response type for native.hid_claim.
type NativeHidClaimResponse struct {
	Success bool `json:"success"`
}

// NativeHidDevicesResponse is the response type for native.hid_devices.
type NativeHidDevicesResponse struct {
	Devices []HidDeviceEntry `json:"devices"`
}

// NativeHidElementsRequest is the request type for native.hid_elements.
type NativeHidElementsRequest struct {
	DeviceID string `json:"device_id"`
}

// NativeHidElementsResponse is the response type for native.hid_elements.
type NativeHidElementsResponse struct {
	Elements []HidElementEntry `json:"elements"`
}

// NativeHidReleaseRequest is the request type for native.hid_release.
type NativeHidReleaseRequest struct {
	DeviceID string `json:"device_id"`
}

// NativeHidReleaseResponse is the response type for native.hid_release.
type NativeHidReleaseResponse struct {
	Success bool `json:"success"`
}

// NativeHidSendReportRequest is the request type for native.hid_send_report.
type NativeHidSendReportRequest struct {
	Data []int `json:"data,omitempty"`
	DeviceID string `json:"device_id"`
	ReportID int `json:"report_id"`
	ReportType string `json:"report_type"`
}

// NativeHidSendReportResponse is the response type for native.hid_send_report.
type NativeHidSendReportResponse struct {
	Success bool `json:"success"`
}

// NativeHideAppRequest is the request type for native.hide_app.
type NativeHideAppRequest struct {
	BundleID string `json:"bundle_id"`
}

// NativeHideAppResponse is the response type for native.hide_app.
type NativeHideAppResponse struct {
	Ok bool `json:"ok"`
}

// NativeInstalledAppsResponse is the response type for native.installed_apps.
type NativeInstalledAppsResponse struct {
	Apps []InstalledApp `json:"apps"`
}

// NativeIsAppHiddenRequest is the request type for native.is_app_hidden.
type NativeIsAppHiddenRequest struct {
	BundleID string `json:"bundle_id"`
}

// NativeIsAppHiddenResponse is the response type for native.is_app_hidden.
type NativeIsAppHiddenResponse struct {
	Result bool `json:"result"`
}

// NativeKeyboardLayoutResponse is the response type for native.keyboard_layout.
type NativeKeyboardLayoutResponse struct {
	LayoutID string `json:"layout_id"`
	LayoutName string `json:"layout_name"`
	Mappings map[string]string `json:"mappings"`
}

// NativeLaunchAppRequest is the request type for native.launch_app.
type NativeLaunchAppRequest struct {
	BundleID string `json:"bundle_id"`
	NewInstance *bool `json:"new_instance,omitempty"`
}

// NativeLaunchAppResponse is the response type for native.launch_app.
type NativeLaunchAppResponse struct {
	Ok bool `json:"ok"`
}

// NativeListNotificationsResponse is the response type for native.list_notifications.
type NativeListNotificationsResponse struct {
	Notifications []DeliveredNotification `json:"notifications"`
}

// NativeListSpacesResponse is the response type for native.list_spaces.
type NativeListSpacesResponse struct {
	Spaces []SpaceInfo `json:"spaces"`
}

// NativeLoginItemsResponse is the response type for native.login_items.
type NativeLoginItemsResponse struct {
	Items []LoginItem `json:"items"`
}

// NativeMenuBarRequest is the request type for native.menu_bar.
type NativeMenuBarRequest struct {
	Pid int `json:"pid"`
}

// NativeMenuBarResponse is the response type for native.menu_bar.
type NativeMenuBarResponse struct {
	Items []MenuItem `json:"items"`
}

// NativeMinimizeWindowRequest is the request type for native.minimize_window.
type NativeMinimizeWindowRequest struct {
	WindowID string `json:"window_id"`
}

// NativeMinimizeWindowResponse is the response type for native.minimize_window.
type NativeMinimizeWindowResponse struct {
	Ok bool `json:"ok"`
}

// NativeMoveWindowToDisplayRequest is the request type for native.move_window_to_display.
type NativeMoveWindowToDisplayRequest struct {
	DisplayID int `json:"display_id"`
	WindowID string `json:"window_id"`
}

// NativeMoveWindowToDisplayResponse is the response type for native.move_window_to_display.
type NativeMoveWindowToDisplayResponse struct {
	Ok bool `json:"ok"`
}

// NativeMoveWindowToSpaceRequest is the request type for native.move_window_to_space.
type NativeMoveWindowToSpaceRequest struct {
	SpaceID int `json:"space_id"`
	WindowID string `json:"window_id"`
}

// NativeMoveWindowToSpaceResponse is the response type for native.move_window_to_space.
type NativeMoveWindowToSpaceResponse struct {
	Result bool `json:"result"`
}

// NativeMuteRequest is the request type for native.mute.
type NativeMuteRequest struct {
	Muted bool `json:"muted"`
}

// NativeMuteResponse is the response type for native.mute.
type NativeMuteResponse struct {
	Ok bool `json:"ok"`
}

// NativeNotifyRequest is the request type for native.notify.
type NativeNotifyRequest struct {
	Body json.RawMessage `json:"body,omitempty"`
	Sound json.RawMessage `json:"sound,omitempty"`
	Subtitle json.RawMessage `json:"subtitle,omitempty"`
	Title string `json:"title"`
}

// NativeNotifyResponse is the response type for native.notify.
type NativeNotifyResponse struct {
	ID json.RawMessage `json:"id,omitempty"`
}

// NativeObserveWindowsRequest is the request type for native.observe_windows.
type NativeObserveWindowsRequest struct {
	Pid int `json:"pid"`
}

// NativeObserveWindowsResponse is the response type for native.observe_windows.
type NativeObserveWindowsResponse struct {
	SubscriptionID string `json:"subscription_id"`
}

// NativeOpenTargetRequest is the request type for native.open_target.
type NativeOpenTargetRequest struct {
	Target string `json:"target"`
}

// NativeOpenTargetResponse is the response type for native.open_target.
type NativeOpenTargetResponse struct {
	Ok bool `json:"ok"`
}

// NativePlaySoundRequest is the request type for native.play_sound.
type NativePlaySoundRequest struct {
	Name string `json:"name"`
}

// NativePlaySoundResponse is the response type for native.play_sound.
type NativePlaySoundResponse struct {
	Ok bool `json:"ok"`
}

// NativePollBurstResponse is the response type for native.poll_burst.
type NativePollBurstResponse struct {
	Ok bool `json:"ok"`
}

// NativePreventSleepRequest is the request type for native.prevent_sleep.
type NativePreventSleepRequest struct {
	AssertionID json.RawMessage `json:"assertion_id,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

// NativePreventSleepResponse is the response type for native.prevent_sleep.
type NativePreventSleepResponse struct {
	AssertionID string `json:"assertion_id"`
}

// NativeQuickLookRequest is the request type for native.quick_look.
type NativeQuickLookRequest struct {
	Path string `json:"path"`
	Size *int `json:"size,omitempty"`
}

// NativeQuickLookResponse is the response type for native.quick_look.
type NativeQuickLookResponse struct {
	Format string `json:"format"`
	ImageBase64 string `json:"image_base64"`
}

// NativeQuitAppRequest is the request type for native.quit_app.
type NativeQuitAppRequest struct {
	BundleID string `json:"bundle_id"`
}

// NativeQuitAppResponse is the response type for native.quit_app.
type NativeQuitAppResponse struct {
	Result bool `json:"result"`
}

// NativeRaiseWindowRequest is the request type for native.raise_window.
type NativeRaiseWindowRequest struct {
	WindowID string `json:"window_id"`
}

// NativeRaiseWindowResponse is the response type for native.raise_window.
type NativeRaiseWindowResponse struct {
	Ok bool `json:"ok"`
}

// NativeRevealInFinderRequest is the request type for native.reveal_in_finder.
type NativeRevealInFinderRequest struct {
	Path string `json:"path"`
}

// NativeRevealInFinderResponse is the response type for native.reveal_in_finder.
type NativeRevealInFinderResponse struct {
	Ok bool `json:"ok"`
}

// NativeRunApplescriptRequest is the request type for native.run_applescript.
type NativeRunApplescriptRequest struct {
	Script string `json:"script"`
}

// NativeRunApplescriptResponse is the response type for native.run_applescript.
type NativeRunApplescriptResponse struct {
	ExitCode int `json:"exit_code"`
	Stderr string `json:"stderr"`
	Stdout string `json:"stdout"`
}

// NativeRunningAppsResponse is the response type for native.running_apps.
type NativeRunningAppsResponse struct {
	Apps []RunningApp `json:"apps"`
}

// NativeScreenLockResponse is the response type for native.screen_lock.
type NativeScreenLockResponse struct {
	Ok bool `json:"ok"`
}

// NativeScreenshotRequest is the request type for native.screenshot.
type NativeScreenshotRequest struct {
	DisplayID json.RawMessage `json:"display_id,omitempty"`
	Region json.RawMessage `json:"region,omitempty"`
	WindowID json.RawMessage `json:"window_id,omitempty"`
}

// NativeScreenshotResponse is the response type for native.screenshot.
type NativeScreenshotResponse struct {
	Format string `json:"format"`
	ImageBase64 string `json:"image_base64"`
}

// NativeSelectedFinderItemsResponse is the response type for native.selected_finder_items.
type NativeSelectedFinderItemsResponse struct {
	Paths []string `json:"paths"`
}

// NativeSetAudioDeviceRequest is the request type for native.set_audio_device.
type NativeSetAudioDeviceRequest struct {
	DeviceType string `json:"device_type"`
	UID string `json:"uid"`
}

// NativeSetAudioDeviceResponse is the response type for native.set_audio_device.
type NativeSetAudioDeviceResponse struct {
	Ok bool `json:"ok"`
}

// NativeSetBrightnessRequest is the request type for native.set_brightness.
type NativeSetBrightnessRequest struct {
	Brightness float64 `json:"brightness"`
	DisplayID json.RawMessage `json:"display_id,omitempty"`
}

// NativeSetBrightnessResponse is the response type for native.set_brightness.
type NativeSetBrightnessResponse struct {
	Ok bool `json:"ok"`
}

// NativeSetDarkModeRequest is the request type for native.set_dark_mode.
type NativeSetDarkModeRequest struct {
	Dark bool `json:"dark"`
}

// NativeSetDarkModeResponse is the response type for native.set_dark_mode.
type NativeSetDarkModeResponse struct {
	Ok bool `json:"ok"`
}

// NativeSetDndRequest is the request type for native.set_dnd.
type NativeSetDndRequest struct {
	Enabled bool `json:"enabled"`
}

// NativeSetDndResponse is the response type for native.set_dnd.
type NativeSetDndResponse struct {
	Ok bool `json:"ok"`
}

// NativeSetVolumeRequest is the request type for native.set_volume.
type NativeSetVolumeRequest struct {
	Volume float64 `json:"volume"`
}

// NativeSetVolumeResponse is the response type for native.set_volume.
type NativeSetVolumeResponse struct {
	Ok bool `json:"ok"`
}

// NativeSetWindowAlphaRequest is the request type for native.set_window_alpha.
type NativeSetWindowAlphaRequest struct {
	Alpha float64 `json:"alpha"`
	WindowID string `json:"window_id"`
}

// NativeSetWindowAlphaResponse is the response type for native.set_window_alpha.
type NativeSetWindowAlphaResponse struct {
	Ok bool `json:"ok"`
}

// NativeSetWindowLevelRequest is the request type for native.set_window_level.
type NativeSetWindowLevelRequest struct {
	Level string `json:"level"`
	WindowID string `json:"window_id"`
}

// NativeSetWindowLevelResponse is the response type for native.set_window_level.
type NativeSetWindowLevelResponse struct {
	Result bool `json:"result"`
}

// NativeSpeakRequest is the request type for native.speak.
type NativeSpeakRequest struct {
	Rate json.RawMessage `json:"rate,omitempty"`
	Text string `json:"text"`
	Voice json.RawMessage `json:"voice,omitempty"`
}

// NativeSpeakResponse is the response type for native.speak.
type NativeSpeakResponse struct {
	Ok bool `json:"ok"`
}

// NativeSpotlightRequest is the request type for native.spotlight.
type NativeSpotlightRequest struct {
	Limit *int `json:"limit,omitempty"`
	Query string `json:"query"`
	Scope json.RawMessage `json:"scope,omitempty"`
}

// NativeSpotlightResponse is the response type for native.spotlight.
type NativeSpotlightResponse struct {
	Results []SpotlightResult `json:"results"`
}

// NativeSystemUptimeResponse is the response type for native.system_uptime.
type NativeSystemUptimeResponse struct {
	Formatted string `json:"formatted"`
	UptimeSeconds float64 `json:"uptime_seconds"`
}

// NativeToggleFullscreenRequest is the request type for native.toggle_fullscreen.
type NativeToggleFullscreenRequest struct {
	WindowID string `json:"window_id"`
}

// NativeToggleFullscreenResponse is the response type for native.toggle_fullscreen.
type NativeToggleFullscreenResponse struct {
	Ok bool `json:"ok"`
}

// NativeTrashRequest is the request type for native.trash.
type NativeTrashRequest struct {
	Path string `json:"path"`
}

// NativeTrashResponse is the response type for native.trash.
type NativeTrashResponse struct {
	Result bool `json:"result"`
}

// NativeUnhideAppRequest is the request type for native.unhide_app.
type NativeUnhideAppRequest struct {
	BundleID string `json:"bundle_id"`
}

// NativeUnhideAppResponse is the response type for native.unhide_app.
type NativeUnhideAppResponse struct {
	Ok bool `json:"ok"`
}

// NativeUnminimizeWindowRequest is the request type for native.unminimize_window.
type NativeUnminimizeWindowRequest struct {
	WindowID string `json:"window_id"`
}

// NativeUnminimizeWindowResponse is the response type for native.unminimize_window.
type NativeUnminimizeWindowResponse struct {
	Ok bool `json:"ok"`
}

// NativeUnobserveWindowsRequest is the request type for native.unobserve_windows.
type NativeUnobserveWindowsRequest struct {
	SubscriptionID string `json:"subscription_id"`
}

// NativeUnobserveWindowsResponse is the response type for native.unobserve_windows.
type NativeUnobserveWindowsResponse struct {
	Result bool `json:"result"`
}

// NativeVolumeResponse is the response type for native.volume.
type NativeVolumeResponse struct {
	IsMuted bool `json:"is_muted"`
	Volume float64 `json:"volume"`
}

// NativeWarpCursorRequest is the request type for native.warp_cursor.
type NativeWarpCursorRequest struct {
	X int `json:"x"`
	Y int `json:"y"`
}

// NativeWarpCursorResponse is the response type for native.warp_cursor.
type NativeWarpCursorResponse struct {
	Ok bool `json:"ok"`
}

// NativeWifiResponse is the response type for native.wifi.
type NativeWifiResponse struct {
	Bssid json.RawMessage `json:"bssid,omitempty"`
	IsConnected bool `json:"is_connected"`
	IsEnabled bool `json:"is_enabled"`
	Rssi json.RawMessage `json:"rssi,omitempty"`
	Ssid json.RawMessage `json:"ssid,omitempty"`
}

// NativeWorldModelRequest is the request type for native.world_model.
type NativeWorldModelRequest struct {
	OnScreen *bool `json:"on_screen,omitempty"`
}

// SelectionPickRequest is the request type for selection.pick.
type SelectionPickRequest struct {
	Index int `json:"index"`
}

// SelectionPickResponse is the response type for selection.pick.
type SelectionPickResponse struct {
	ControlMessage string `json:"control_message"`
	ItemID string `json:"item_id"`
	Ok bool `json:"ok"`
	ResetEngine bool `json:"reset_engine"`
}

// SelectionSetRequest is the request type for selection.set.
type SelectionSetRequest struct {
	Channel json.RawMessage `json:"channel,omitempty"`
	Items json.RawMessage `json:"items,omitempty"`
	Title json.RawMessage `json:"title,omitempty"`
}

// SelectionSetResponse is the response type for selection.set.
type SelectionSetResponse struct {
	Ok bool `json:"ok"`
}

// SessionEndCleanupResponse is the response type for session.end_cleanup.
type SessionEndCleanupResponse struct {
	ControlMessage json.RawMessage `json:"control_message,omitempty"`
	Ok bool `json:"ok"`
	ResetEngine bool `json:"reset_engine"`
}

// SettingsPatchSignalsRequest is the request type for settings.patch_signals.
type SettingsPatchSignalsRequest struct {
	Signals string `json:"signals"`
}

// SettingsPatchSignalsResponse is the response type for settings.patch_signals.
type SettingsPatchSignalsResponse struct {
	Ok bool `json:"ok"`
}

// SettingsRulesCreateRequest is the request type for settings.rules_create.
type SettingsRulesCreateRequest struct {
	Newruleactionjson json.RawMessage `json:"newruleactionjson,omitempty"`
	Newruleactiontype json.RawMessage `json:"newruleactiontype,omitempty"`
	Newruleactionval json.RawMessage `json:"newruleactionval,omitempty"`
	Newrulecategory json.RawMessage `json:"newrulecategory,omitempty"`
	Newruleclearstags json.RawMessage `json:"newruleclearstags,omitempty"`
	Newruledescription json.RawMessage `json:"newruledescription,omitempty"`
	Newrulephrase json.RawMessage `json:"newrulephrase,omitempty"`
	Newrulerequirestags json.RawMessage `json:"newrulerequirestags,omitempty"`
	Newrulesetstags json.RawMessage `json:"newrulesetstags,omitempty"`
}

// SettingsRulesCreateResponse is the response type for settings.rules_create.
type SettingsRulesCreateResponse struct {
	Ok bool `json:"ok"`
}

// SettingsRulesUpdateRequest is the request type for settings.rules_update.
type SettingsRulesUpdateRequest struct {
	Canonical string `json:"canonical"`
	Newruleactionjson json.RawMessage `json:"newruleactionjson,omitempty"`
	Newruleactiontype json.RawMessage `json:"newruleactiontype,omitempty"`
	Newruleactionval json.RawMessage `json:"newruleactionval,omitempty"`
	Newrulecategory json.RawMessage `json:"newrulecategory,omitempty"`
	Newruleclearstags json.RawMessage `json:"newruleclearstags,omitempty"`
	Newruledescription json.RawMessage `json:"newruledescription,omitempty"`
	Newrulephrase json.RawMessage `json:"newrulephrase,omitempty"`
	Newrulerequirestags json.RawMessage `json:"newrulerequirestags,omitempty"`
	Newrulesetstags json.RawMessage `json:"newrulesetstags,omitempty"`
}

// SettingsRulesUpdateResponse is the response type for settings.rules_update.
type SettingsRulesUpdateResponse struct {
	Ok bool `json:"ok"`
}

// SystemLaunchAppRequest is the request type for system.launch_app.
type SystemLaunchAppRequest struct {
	BundleID string `json:"bundle_id"`
	NewInstance *bool `json:"new_instance,omitempty"`
}

// SystemLaunchAppResponse is the response type for system.launch_app.
type SystemLaunchAppResponse struct {
	Ok bool `json:"ok"`
}

// SystemNotifyRequest is the request type for system.notify.
type SystemNotifyRequest struct {
	Body string `json:"body"`
	DurationSecs json.RawMessage `json:"duration_secs,omitempty"`
	Title string `json:"title"`
}

// SystemNotifyResponse is the response type for system.notify.
type SystemNotifyResponse struct {
	Ok bool `json:"ok"`
}

// SystemRunShellRequest is the request type for system.run_shell.
type SystemRunShellRequest struct {
	Command string `json:"command"`
}

// SystemRunShellResponse is the response type for system.run_shell.
type SystemRunShellResponse struct {
	Ok bool `json:"ok"`
}

// TagsGetResponse is the response type for tags.get.
type TagsGetResponse struct {
	Tags []string `json:"tags"`
}

// TagsModifyRequest is the request type for tags.modify.
type TagsModifyRequest struct {
	Clear []string `json:"clear,omitempty"`
	ClearScoped *bool `json:"clear_scoped,omitempty"`
	Set []string `json:"set,omitempty"`
}

// TagsModifyResponse is the response type for tags.modify.
type TagsModifyResponse struct {
	Tags []string `json:"tags"`
}

// ===== Actuator → Plugin request/response types =====

// OnActionRequest is the request type for on_action.
type OnActionRequest struct {
	Action string `json:"action"`
	ActiveApp *string `json:"active_app,omitempty"`
	ActiveWindowID *string `json:"active_window_id,omitempty"`
	Params json.RawMessage `json:"params,omitempty"`
}

// OnActionResponse is the response type for on_action.
type OnActionResponse struct {
	ControlMessage *string `json:"control_message,omitempty"`
	Result json.RawMessage `json:"result,omitempty"`
	Status OnActionStatus `json:"status"`
}

// OnCommandsChangedRequest is the request type for on_commands_changed.
type OnCommandsChangedRequest struct {
	CommandsByPlugin json.RawMessage `json:"commands_by_plugin"`
	UserCommands []json.RawMessage `json:"user_commands,omitempty"`
}

// OnCommandsChangedResponse is the response type for on_commands_changed.
type OnCommandsChangedResponse struct {
	ProcessedCount int `json:"processed_count"`
}

// RenderHUDRequest is the request type for render_hud.
type RenderHUDRequest struct {
	Footer *string `json:"footer,omitempty"`
	HudMode string `json:"hud_mode"`
	Sections []HudSection `json:"sections,omitempty"`
	Title *string `json:"title,omitempty"`
}

// RenderSettingsRequest is the request type for render_settings.
type RenderSettingsRequest struct {
	ActionTypeSchemas map[string]ActionTypeSchema `json:"action_type_schemas,omitempty"`
	CollectionData map[string]json.RawMessage `json:"collection_data,omitempty"`
	CommandFilter *string `json:"command_filter,omitempty"`
	Commands []CommandRowData `json:"commands,omitempty"`
	ListSchemas map[string]SettingsListSchemaInfo `json:"list_schemas,omitempty"`
	Search string `json:"search"`
	TabKey string `json:"tab_key"`
	TagSchemas map[string]SettingsTagSchemaInfo `json:"tag_schemas,omitempty"`
}

// RenderSettingsResponse is the response type for render_settings.
type RenderSettingsResponse struct {
	HTML string `json:"html"`
}

// SpeechPipelineFullRequest is the request type for speech_pipeline_full.
type SpeechPipelineFullRequest struct {
	ChannelVisibility map[string]bool `json:"channel_visibility,omitempty"`
	IsContinuous *bool `json:"is_continuous,omitempty"`
	IsFinal bool `json:"is_final"`
	MuteMatching *bool `json:"mute_matching,omitempty"`
	ScopedPrefixes []string `json:"scoped_prefixes,omitempty"`
	Segments []IngestSegmentSpec `json:"segments"`
	SelectionActive *bool `json:"selection_active,omitempty"`
	SelectionItems []SelectionItemSpec `json:"selection_items,omitempty"`
	SessionEnd bool `json:"session_end"`
	SessionID json.RawMessage `json:"session_id,omitempty"`
	ShouldLift *bool `json:"should_lift,omitempty"`
	Tags []string `json:"tags,omitempty"`
}

// SpeechPipelineFullResponse is the response type for speech_pipeline_full.
type SpeechPipelineFullResponse struct {
	ControlMessage json.RawMessage `json:"control_message,omitempty"`
	PasteText json.RawMessage `json:"paste_text,omitempty"`
	ResetEngine *bool `json:"reset_engine,omitempty"`
	Status *string `json:"status,omitempty"`
}
