// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.
//
// Transport vocabulary: the handshake, framing, error and flow-credit
// types every stage speaks whatever its domain.

package pipeline

import (
	"encoding/json"
	"strings"

	"github.com/branchkit/plugin-sdk-go/pipeline/audio"
)

// Ensure the json import is used even if no type needs it.
var _ json.RawMessage

// Wire event tags. Use these instead of string literals so vocabulary
// drift is a compile error.
const (
	EventCapability = "capability"
	EventError      = "error"
	EventFlowCredit = "flow_credit"
)

// ExtEventPrefix reserves the open namespace a stage emits custom events
// under: at least three non-empty dot segments, `ext.<vendor>.<name>`.
//
// This is the namespace EVERY domain the platform does not itself decode
// lives in — a foot pedal, a frame source, a MIDI filter. It needs no
// platform change and no entry in any catalog.
const ExtEventPrefix = "ext."

// IsValidExtEventType reports whether a custom event type is well-formed.
func IsValidExtEventType(t string) bool {
	if !strings.HasPrefix(t, ExtEventPrefix) {
		return false
	}
	parts := strings.Split(t, ".")
	if len(parts) < 3 {
		return false
	}
	for _, p := range parts {
		if p == "" {
			return false
		}
	}
	return true
}

// Environment variables the platform sets when it spawns a stage.
// NEVER re-derive these paths: the sandbox grants access by the path the
// platform computed, so a second spelling is a denial that reads like a
// missing directory.
const (
	ModelsDirEnv = "BRANCHKIT_MODELS_DIR"
	DataDirEnv   = "BRANCHKIT_STAGE_DATA"
)

type Capability struct {
	AudioFormats []audio.AudioFormat `json:"audio_formats,omitempty"`
	// Event types this stage emits — built-in tags (`transcript`,
	// `power_snapshot`, …) and/or custom types under [`EXT_EVENT_PREFIX`]
	// (an `ext.<vendor>.*` glob covers a vendor namespace). Advisory at
	// runtime (the platform logs undeclared `ext.*` emissions rather than
	// dropping them); enforced by the conformance harness. Empty = the
	// stage declares nothing (pre-existing stages).
	Emits          []string       `json:"emits,omitempty"`
	FeatureFlags   map[string]any `json:"feature_flags,omitempty"`
	LifecycleModes []string       `json:"lifecycle_modes"`
	StageName      string         `json:"stage_name"`
	StageType      string         `json:"stage_type"`
}

type ErrorEvent struct {
	Code      string  `json:"code"`
	Fatal     bool    `json:"fatal"`
	Message   string  `json:"message"`
	SessionId *string `json:"session_id,omitempty"`
}

type FlowCredit struct {
	Frames    uint32 `json:"frames"`
	SessionId string `json:"session_id"`
}

// The serialized header line — one JSON object per event, newline-terminated,
// followed by exactly `payload_length` raw bytes when non-zero. `data` is
// omitted when empty/null; `payload_length` is omitted when zero.
type WireHeader struct {
	Data          json.RawMessage `json:"data,omitempty"`
	PayloadLength *uint           `json:"payload_length,omitempty"`
	Type          string          `json:"type"`
}
