// AUTO-GENERATED by emit-stage-sdk — do not edit.
// Run: just gen-stage-sdk
//
// The BranchKit pipeline event vocabulary, projected from
// contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
// types). Framing lives in the hand-written reader/writer alongside this file.
//
// First-party monitor families. Typed because the platform renames them
// onto its bus as `_platform.*` events; a third-party monitor uses
// `ext.<vendor>.*` instead and needs nothing from here.

package monitors

import (
	"encoding/json"
)

// Ensure the json import is used even if no type needs it.
var _ json.RawMessage

// Wire event tags. Use these instead of string literals so vocabulary
// drift is a compile error.
const (
	EventAudioDeviceAdded          = "audio_device_added"
	EventAudioDeviceDefaultChanged = "audio_device_default_changed"
	EventAudioDeviceRemoved        = "audio_device_removed"
	EventAudioDeviceSnapshot       = "audio_device_snapshot"
	EventDisplayAdded              = "display_added"
	EventDisplayChanged            = "display_changed"
	EventDisplayRemoved            = "display_removed"
	EventDisplaySnapshot           = "display_snapshot"
	EventHeadingUpdate             = "heading_update"
	EventLocationError             = "location_error"
	EventLocationUpdate            = "location_update"
	EventPowerSnapshot             = "power_snapshot"
	EventPowerSourceChanged        = "power_source_changed"
)

type AudioDeviceAdded struct {
	Device AudioDeviceInfo `json:"device"`
}

type AudioDeviceDefaultChanged struct {
	DeviceId  uint32 `json:"device_id"`
	Direction string `json:"direction"`
	Name      string `json:"name"`
	Uid       string `json:"uid"`
}

type AudioDeviceInfo struct {
	DeviceId        uint32 `json:"device_id"`
	IsDefaultInput  bool   `json:"is_default_input"`
	IsDefaultOutput bool   `json:"is_default_output"`
	IsInput         bool   `json:"is_input"`
	IsOutput        bool   `json:"is_output"`
	Name            string `json:"name"`
	Uid             string `json:"uid"`
}

type AudioDeviceRemoved struct {
	DeviceId uint32 `json:"device_id"`
	Name     string `json:"name"`
	Uid      string `json:"uid"`
}

type AudioDeviceSnapshot struct {
	Devices []AudioDeviceInfo `json:"devices"`
}

type DisplayAdded struct {
	Display DisplayInfo `json:"display"`
}

type DisplayChanged struct {
	Display DisplayInfo `json:"display"`
}

type DisplayInfo struct {
	DisplayId   uint32  `json:"display_id"`
	Height      uint32  `json:"height"`
	IsBuiltin   bool    `json:"is_builtin"`
	IsMain      bool    `json:"is_main"`
	RefreshRate float64 `json:"refresh_rate"`
	ScaleFactor float64 `json:"scale_factor"`
	Width       uint32  `json:"width"`
}

type DisplayRemoved struct {
	DisplayId uint32 `json:"display_id"`
}

type DisplaySnapshot struct {
	Displays []DisplayInfo `json:"displays"`
}

type HeadingUpdate struct {
	HeadingAccuracy float64 `json:"heading_accuracy"`
	MagneticHeading float64 `json:"magnetic_heading"`
	Timestamp       float64 `json:"timestamp"`
	TrueHeading     float64 `json:"true_heading"`
}

type LocationError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type LocationUpdate struct {
	Altitude           float64 `json:"altitude"`
	HorizontalAccuracy float64 `json:"horizontal_accuracy"`
	Latitude           float64 `json:"latitude"`
	Longitude          float64 `json:"longitude"`
	Timestamp          float64 `json:"timestamp"`
	VerticalAccuracy   float64 `json:"vertical_accuracy"`
}

type PowerSnapshot struct {
	State PowerState `json:"state"`
}

type PowerSourceChanged struct {
	State PowerState `json:"state"`
}

type PowerState struct {
	BatteryLevel *float64 `json:"battery_level,omitempty"`
	IsCharging   bool     `json:"is_charging"`
	Source       string   `json:"source"`
	TimeToEmpty  *int64   `json:"time_to_empty,omitempty"`
	TimeToFull   *int64   `json:"time_to_full,omitempty"`
}
